-- ============================================================================
-- Seed: Curatela / Capacidade Civil
-- ============================================================================
-- Gerado a partir de "Padrão PERICONS — Laudo Médico-Pericial Judicial de
-- Capacidade Civil e Curatela" (Laudos e documentos/). 19 seções (I-XIX),
-- sem contar o endereçamento formal + Apresentação (que ficam fora das telas
-- de preenchimento, só no documento final compilado, conforme CLAUDE.md).
--
-- Achados ao mapear este modelo (ver resumo enviado à Dra. Fernanda p/ conferência):
--  - Não há, neste modelo, o padrão "exame físico por sistema fechado por padrão
--    com 4 opções" — nenhum campo usa parent_campo_id/condicao aqui.
--  - Nenhuma das 19 seções é condicional neste modelo (condicional = false em todas).
--  - Seções VI (Matriz de Documentos Analisados) e XVII (Respostas aos Quesitos)
--    são estruturais: 0 campos_secao. VI é servida por `documentos` (categoria,
--    origem_profissional, data_documento, paginas); XVII por `quesitos`.
--  - texto_automatico_template usa {{codigo_do_campo}} (pode referenciar campo de
--    qualquer seção deste tipo_laudo) ou tokens computados pela aplicação quando não
--    há campo 1:1 (ex.: {{total_documentos}}, {{achados_clinicos_principais}}) —
--    marcados nos comentários abaixo.
--  - selecao_unica vs selecao_multipla: o PDF usa "[ ]" para ambos os casos sem
--    distinguir visualmente; a escolha abaixo segue a heurística do CLAUDE.md
--    (mutuamente excludente = única; sintomas/achados/exposições combináveis =
--    múltipla). Vale conferir contra o seu julgamento clínico no resumo seção a seção.
--
-- Correção pós-teste do preenchimento (Etapa 4): o texto_automatico_template da
-- Seção X (Exame do Estado Mental) usava placeholders "resumo"
-- ({{orientacao}}, {{memoria}}, {{pensamento}}, {{funcoes_executivas}}) que não
-- correspondiam a nenhum campos_secao.codigo real — só existiam os sub-itens
-- (orientacao_temporal, memoria_imediata, pensamento_curso, funcao_executiva_*
-- etc.), então esses 4 trechos nunca eram substituídos. Reescrito pra
-- referenciar os codigos reais. Se este seed for rodado de novo do zero, já
-- sai correto; quem já tiver a Seção X seedada precisa também da migration
-- 20260823120000_fix_texto_automatico_estado_mental.sql (faz o UPDATE na
-- linha já existente).
-- ============================================================================

insert into public.tipos_laudo (id, codigo, nome, descricao, ordem, ativo) values
  ('69f4d401-317b-507b-b501-c0e872b07a43', 'curatela', 'Curatela / Capacidade Civil',
   'Avaliação médico-pericial judicial da capacidade civil e curatela.', 1, true);

insert into public.secoes (id, tipo_laudo_id, codigo, titulo, ordem, condicional, condicao, texto_automatico_template) values
  ('38082c22-b6ec-570d-972e-4274506336aa', '69f4d401-317b-507b-b501-c0e872b07a43', 'identificacao_perito', 'I — Identificação do(a) Perito(a) Judicial', 1, false, null, null),
  ('4c392dae-f4f7-5122-ab5a-eb38c0e26c03', '69f4d401-317b-507b-b501-c0e872b07a43', 'identificacao_periciando', 'II — Identificação do(a) Periciando(a)', 2, false, null, null),
  ('17dd4988-565a-55cd-9600-f3f38423148b', '69f4d401-317b-507b-b501-c0e872b07a43', 'presentes_fontes_informacao', 'III — Presentes ao Ato Pericial e Fontes de Informação', 3, false, null, null),
  ('615821e2-6df2-5113-a17a-c59dfbaf344b', '69f4d401-317b-507b-b501-c0e872b07a43', 'objeto_pericia', 'IV — Objeto da Perícia', 4, false, null, 'Sob a perspectiva médico-legal, objetiva-se avaliar a existência de condição clínica capaz de repercutir sobre a autonomia e a capacidade civil do(a) periciando(a), especialmente quanto à sua aptidão para compreender informações relevantes, avaliar consequências, deliberar, manifestar vontade e praticar autonomamente atos da vida civil, indicando-se, quando tecnicamente possível, os domínios eventualmente comprometidos e a necessidade de apoio de terceiros.'),
  ('f3c3fe51-0873-5b0c-a9e5-c98d952e8437', '69f4d401-317b-507b-b501-c0e872b07a43', 'metodologia_pericial', 'V — Metodologia Pericial', 5, false, null, 'A conclusão médico-pericial resulta da integração entre os dados documentais, clínicos, cognitivos, comportamentais e funcionais obtidos durante a avaliação, considerada sua pertinência ao objeto determinado pelo Juízo.'),
  ('df7868ed-f7bb-532f-9671-6ca115ea182a', '69f4d401-317b-507b-b501-c0e872b07a43', 'matriz_documentos_analisados', 'VI — Matriz dos Documentos Analisados', 6, false, null, 'Foram analisados {{total_documentos}} documentos, totalizando {{total_paginas}} páginas, compreendendo {{categorias_principais}}, considerados em conjunto com os achados obtidos durante o exame pericial.'),
  ('2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', '69f4d401-317b-507b-b501-c0e872b07a43', 'historia_clinica', 'VII — Reconstrução da História Clínica', 7, false, null, 'Conforme as informações obtidas, o(a) periciando(a) apresenta quadro de {{diagnostico_informado}}, com início {{inicio_condicao}}, evolução {{curso_clinico}} e manifestações predominantemente caracterizadas por {{manifestacoes_predominantes}}.'),
  ('2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', '69f4d401-317b-507b-b501-c0e872b07a43', 'antecedentes_tratamentos', 'VIII — Antecedentes e Tratamentos', 8, false, null, null),
  ('27fbf857-417c-5198-894f-cb2b70abc9ea', '69f4d401-317b-507b-b501-c0e872b07a43', 'exame_clinico_geral', 'IX — Exame Clínico Geral', 9, false, null, 'Ao exame clínico geral, apresentou-se em estado geral {{estado_geral}}, com apresentação pessoal {{apresentacao_pessoal}}, higiene {{higiene}}, locomoção {{locomocao}} e comunicação {{comunicacao}}. Durante a avaliação mostrou-se {{cooperacao_exame}} às solicitações periciais.'),
  ('2c2d3d72-c0c3-5846-9f38-37978db3e408', '69f4d401-317b-507b-b501-c0e872b07a43', 'exame_estado_mental', 'X — Exame do Estado Mental', 10, false, null, 'Ao exame do estado mental, o(a) periciando(a) apresentou-se {{consciencia}}, com orientação autopsíquica {{orientacao_autopsiquica}}, temporal {{orientacao_temporal}}, espacial {{orientacao_espacial}} e situacional {{orientacao_situacional}}, atenção e concentração {{atencao_concentracao}}, memória imediata {{memoria_imediata}}, recente {{memoria_recente}} e remota {{memoria_remota}}, linguagem {{linguagem}} e pensamento com curso {{pensamento_curso}}, forma {{pensamento_forma}} e conteúdo {{pensamento_conteudo}}. O juízo crítico mostrou-se {{juizo_critico}}, o insight {{insight}}, observando-se funções executivas — planejamento {{funcao_executiva_planejamento}}, organização {{funcao_executiva_organizacao}}, resolução de problemas {{funcao_executiva_resolucao_problemas}} e flexibilidade cognitiva {{funcao_executiva_flexibilidade_cognitiva}} — e capacidade de abstração {{capacidade_abstracao}}.'),
  ('f3c251ab-d2ce-5696-89d4-06a3f15f8c9c', '69f4d401-317b-507b-b501-c0e872b07a43', 'avaliacao_cognitiva_complementar', 'XI — Avaliação Cognitiva Complementar', 11, false, null, 'Observação: o resultado de instrumento de rastreio cognitivo deverá ser interpretado em conjunto com escolaridade, contexto sociocultural, condições sensoriais, exame clínico e funcionalidade, não sendo utilizado isoladamente para definição de capacidade civil.'),
  ('647490b9-ed73-511f-8f3f-b6ca2a4dc76c', '69f4d401-317b-507b-b501-c0e872b07a43', 'avaliacao_funcionalidade', 'XII — Avaliação da Funcionalidade', 12, false, null, 'Quanto à funcionalidade, apresenta [funcionalidade_abvd_grau] para as atividades básicas da vida diária e [funcionalidade_aivd_grau] de dependência para as atividades instrumentais, necessitando de [funcionalidade_tipo_auxilio] principalmente para [funcionalidade_atividades_criticas].'),
  ('0188ba27-cec7-586d-97e6-2f4b67ae8af7', '69f4d401-317b-507b-b501-c0e872b07a43', 'avaliacao_capacidade_civil_discernimento', 'XIII — Avaliação Específica da Capacidade Civil e do Discernimento', 13, false, null, null),
  ('651f303d-e9d1-55b2-9357-f1d63e642bf8', '69f4d401-317b-507b-b501-c0e872b07a43', 'autonomia_vontade_apoio', 'XIV — Autonomia, Manifestação da Vontade e Necessidade de Apoio', 14, false, null, 'O(a) periciando(a) apresenta capacidade de manifestação da vontade {{manifestacao_vontade}}, com {{suscetibilidade_influencia_indevida}} de suscetibilidade à influência indevida e necessidade de {{necessidade_global_apoio}} para {{dominios_necessita_apoio}}.'),
  ('7fabc9e8-8e47-5e80-9095-8393626f935f', '69f4d401-317b-507b-b501-c0e872b07a43', 'diagnostico_prognostico', 'XV — Diagnóstico Médico-Pericial e Prognóstico', 15, false, null, null),
  ('ff1784c0-5149-5836-a94b-9bea1d7cd633', '69f4d401-317b-507b-b501-c0e872b07a43', 'discussao_medico_legal', 'XVI — Discussão Médico-Legal', 16, false, null, 'A existência de diagnóstico médico não determina, isoladamente, incapacidade civil. A análise médico-pericial deve estabelecer se as alterações clínicas identificadas repercutem concretamente sobre as capacidades necessárias à compreensão, deliberação, manifestação da vontade, autodeterminação e exercício dos atos da vida civil. No caso em análise, o(a) periciando(a) apresenta {{diagnostico_principal}}, caracterizado por [achados_clinicos_principais], observando-se ao exame [alteracoes_cognitivas_psiquicas_principais]. Do ponto de vista funcional, apresenta [grau_autonomia], necessitando de [grau_auxilio] para [atividades_dependentes]. Quanto à capacidade decisória, verifica-se [preservacao_comprometimento_capacidade_decisoria] da capacidade de compreender informações, avaliar consequências, comparar alternativas, manifestar escolhas e reconhecer riscos relacionados aos atos avaliados. A análise conjunta desses elementos permite estabelecer que [sintese_capacidade_civil]. A eventual indicação de curatela deve ser interpretada de maneira individualizada, proporcional às necessidades concretamente identificadas e com preservação máxima possível da autonomia e da manifestação de vontade do(a) periciando(a).'),
  ('e1923e6e-1a37-556a-9f74-bf042707f834', '69f4d401-317b-507b-b501-c0e872b07a43', 'respostas_quesitos', 'XVII — Respostas aos Quesitos', 17, false, null, null),
  ('da60ed75-515d-58cc-b49e-329695df54d1', '69f4d401-317b-507b-b501-c0e872b07a43', 'conclusao_medico_pericial', 'XVIII — Conclusão Médico-Pericial', 18, false, null, null),
  ('60a2b5cb-f4b3-5aec-9931-c6d2c2e5f917', '69f4d401-317b-507b-b501-c0e872b07a43', 'encerramento', 'XIX — Encerramento', 19, false, null, 'O presente laudo representa o entendimento técnico desta Perita Judicial, fundamentado nos elementos disponíveis e nos achados obtidos durante a avaliação médico-pericial, permanecendo esta profissional à disposição do Juízo para eventuais esclarecimentos que se façam necessários.');

insert into public.campos_secao (id, secao_id, parent_campo_id, codigo, rotulo, tipo_campo, ordem, obrigatorio, aceita_texto_livre, opcoes, config_tabela, condicional, condicao, requer_confirmacao_perito) values
  ('92dedc01-91f5-55ee-a05e-82da07532558', '38082c22-b6ec-570d-972e-4274506336aa', null, 'nome_perito', 'Nome', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('2bc0dad4-f216-5d8c-9b76-ec3298359fb5', '38082c22-b6ec-570d-972e-4274506336aa', null, 'crm_uf', 'CRM/UF', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('b28bd182-019f-51a3-bb78-49c60f2e7e16', '38082c22-b6ec-570d-972e-4274506336aa', null, 'especialidade', 'Especialidade', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('fa7f855b-30f8-5299-a370-6eed73991802', '38082c22-b6ec-570d-972e-4274506336aa', null, 'rqe', 'RQE', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('2c45aac7-62d9-56a7-8f8f-8b6088343fa6', '38082c22-b6ec-570d-972e-4274506336aa', null, 'data_nomeacao', 'Data da nomeação', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('e3ef21e4-d7ad-549a-8c41-2536f9631b34', '38082c22-b6ec-570d-972e-4274506336aa', null, 'data_pericia', 'Data da perícia', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('a5e91464-1488-50a3-b21e-2140a3f9795e', '38082c22-b6ec-570d-972e-4274506336aa', null, 'horario_inicio', 'Horário de início', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('0cc98ede-b4aa-5ece-aa77-9335e0d314c6', '38082c22-b6ec-570d-972e-4274506336aa', null, 'horario_termino', 'Horário de término', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('bf28e9a8-8431-51ab-9564-6761e60c325e', '38082c22-b6ec-570d-972e-4274506336aa', null, 'local_pericia', 'Local da perícia', 'selecao_unica', 9, false, true, '[{"codigo": "forum", "rotulo": "Fórum"}, {"codigo": "consultorio", "rotulo": "Consultório"}, {"codigo": "hospital", "rotulo": "Hospital"}, {"codigo": "residencia_periciando", "rotulo": "Residência do(a) periciando(a)"}, {"codigo": "instituicao_longa_permanencia", "rotulo": "Instituição de longa permanência"}, {"codigo": "unidade_saude", "rotulo": "Unidade de saúde"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('d47acf8f-4280-5950-860d-62eaa110fd05', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'nome_completo', 'Nome completo', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('e246964b-88f6-51c4-af07-28d8d85cbc3d', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'data_nascimento', 'Data de nascimento', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('d4b76650-6fb0-5f1a-95e5-b328dd02cee8', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'idade', 'Idade', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('3f2f6318-ff54-5af4-870a-8cf1785f8d04', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'sexo', 'Sexo', 'selecao_unica', 4, false, true, '[{"codigo": "feminino", "rotulo": "Feminino"}, {"codigo": "masculino", "rotulo": "Masculino"}, {"codigo": "outro", "rotulo": "Outro/registro pertinente"}]'::jsonb, null, false, null, false),
  ('b9ebfbb0-6dba-59b4-ac0f-13026092324e', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'estado_civil', 'Estado civil', 'selecao_unica', 5, false, true, '[{"codigo": "solteiro", "rotulo": "Solteiro(a)"}, {"codigo": "casado", "rotulo": "Casado(a)"}, {"codigo": "uniao_estavel", "rotulo": "União estável"}, {"codigo": "divorciado", "rotulo": "Divorciado(a)"}, {"codigo": "separado", "rotulo": "Separado(a)"}, {"codigo": "viuvo", "rotulo": "Viúvo(a)"}, {"codigo": "nao_informado", "rotulo": "Não informado"}]'::jsonb, null, false, null, false),
  ('8d81bd80-4b78-5e92-bb27-2e03d1db2cb6', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'escolaridade', 'Escolaridade', 'selecao_unica', 6, false, true, '[{"codigo": "nao_alfabetizado", "rotulo": "Não alfabetizado(a)"}, {"codigo": "alfabetizacao_informal", "rotulo": "Alfabetização informal"}, {"codigo": "fundamental_incompleto", "rotulo": "Ensino Fundamental incompleto"}, {"codigo": "fundamental_completo", "rotulo": "Ensino Fundamental completo"}, {"codigo": "medio_incompleto", "rotulo": "Ensino Médio incompleto"}, {"codigo": "medio_completo", "rotulo": "Ensino Médio completo"}, {"codigo": "superior_incompleto", "rotulo": "Ensino Superior incompleto"}, {"codigo": "superior_completo", "rotulo": "Ensino Superior completo"}, {"codigo": "pos_graduacao", "rotulo": "Pós-graduação"}, {"codigo": "nao_informado", "rotulo": "Não informado"}]'::jsonb, null, false, null, false),
  ('57398e19-1200-5a25-a5dd-d32ca77a4076', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'profissao_ocupacao_habitual', 'Profissão/ocupação habitual', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('4a1f9483-d496-597b-a13a-b4bdee2ed86b', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'situacao_ocupacional_atual', 'Situação ocupacional atual', 'selecao_unica', 8, false, true, '[{"codigo": "trabalhando", "rotulo": "Trabalhando"}, {"codigo": "afastado", "rotulo": "Afastado(a)"}, {"codigo": "desempregado", "rotulo": "Desempregado(a)"}, {"codigo": "aposentado", "rotulo": "Aposentado(a)"}, {"codigo": "beneficiario_assistencial", "rotulo": "Beneficiário(a) assistencial"}, {"codigo": "nunca_exerceu_atividade_laboral", "rotulo": "Nunca exerceu atividade laboral"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('93dd6aee-da30-55d9-9d2e-d6ef269740f2', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'rg', 'RG', 'texto_livre', 9, false, true, null, null, false, null, false),
  ('6b96113a-c64b-5e0e-a285-4f596b89179a', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'cpf', 'CPF', 'texto_livre', 10, false, true, null, null, false, null, false),
  ('bebc540c-393b-518f-b18e-eaf7b1995c55', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'naturalidade', 'Naturalidade', 'texto_livre', 11, false, true, null, null, false, null, false),
  ('08391298-3bb3-5ff4-a4a1-fbfcf657d3cd', '4c392dae-f4f7-5122-ab5a-eb38c0e26c03', null, 'endereco', 'Endereço', 'texto_livre', 12, false, true, null, null, false, null, false),
  ('059af780-a23f-5454-99c0-6c027653152c', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'presentes_ato_pericial', 'Estiveram presentes durante o ato pericial', 'selecao_multipla', 1, false, true, '[{"codigo": "somente_periciando", "rotulo": "Somente o(a) periciando(a)"}, {"codigo": "requerente", "rotulo": "Requerente"}, {"codigo": "conjuge_companheiro", "rotulo": "Cônjuge/companheiro(a)"}, {"codigo": "pai_mae", "rotulo": "Pai/mãe"}, {"codigo": "filho", "rotulo": "Filho(a)"}, {"codigo": "irmao", "rotulo": "Irmão(ã)"}, {"codigo": "outro_familiar", "rotulo": "Outro familiar"}, {"codigo": "cuidador", "rotulo": "Cuidador(a)"}, {"codigo": "assistente_tecnico", "rotulo": "Assistente técnico"}, {"codigo": "advogado", "rotulo": "Advogado(a)"}, {"codigo": "interprete", "rotulo": "Intérprete"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('78828a60-1e34-50a8-aeac-7178a6e86702', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'nome_principal_informante', 'Nome do principal informante', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('50376e35-ac24-5dc4-8ccc-a0501cc42a14', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'relacao_principal_informante', 'Relação com o(a) periciando(a)', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('1be2c6f4-9aa9-5bf7-ab01-37a2682f72ff', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'fontes_utilizadas', 'Fontes utilizadas', 'selecao_multipla', 4, false, true, '[{"codigo": "relato_direto_periciando", "rotulo": "Relato direto do(a) periciando(a)"}, {"codigo": "heteroanamnese_familiar", "rotulo": "Heteroanamnese com familiar"}, {"codigo": "heteroanamnese_cuidador", "rotulo": "Heteroanamnese com cuidador"}, {"codigo": "documentos_autos", "rotulo": "Documentos constantes dos autos"}, {"codigo": "prontuarios_medicos", "rotulo": "Prontuários médicos"}, {"codigo": "relatorios_medicos", "rotulo": "Relatórios médicos"}, {"codigo": "avaliacao_neuropsicologica", "rotulo": "Avaliação neuropsicológica"}, {"codigo": "relatorios_multiprofissionais", "rotulo": "Relatórios multiprofissionais"}, {"codigo": "outros", "rotulo": "Outros"}]'::jsonb, null, false, null, false),
  ('38e489eb-7798-53f0-9ed0-756363872d9a', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'confiabilidade_informacoes', 'Confiabilidade das informações', 'selecao_unica', 5, false, true, '[{"codigo": "elevada", "rotulo": "Elevada"}, {"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "parcial", "rotulo": "Parcial"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_foi_possivel_aferir", "rotulo": "Não foi possível aferir"}]'::jsonb, null, false, null, false),
  ('55f21424-05e9-53f8-bde0-90b414dc866e', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'justificativa_confiabilidade', 'Justificativa, quando pertinente', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('86f4f0e7-34da-5bdc-9eba-35b07eab9c03', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'interferencia_terceiros', 'Interferência de terceiros durante a avaliação', 'selecao_unica', 7, false, true, '[{"codigo": "nao_observada", "rotulo": "Não observada"}, {"codigo": "discreta", "rotulo": "Discreta"}, {"codigo": "relevante", "rotulo": "Relevante"}, {"codigo": "avaliacao_prejudicada", "rotulo": "Avaliação prejudicada pela interferência"}]'::jsonb, null, false, null, false),
  ('b9306b62-3779-57df-b508-220bb0aa525a', '17dd4988-565a-55cd-9600-f3f38423148b', null, 'descricao_interferencia_terceiros', 'Descrição', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('fd138876-003a-5193-ad79-01c90549f416', '615821e2-6df2-5113-a17a-c59dfbaf344b', null, 'objeto_pericia_importado', 'Objeto da perícia (transcrever/importar da decisão/despacho saneador)', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('37555bbb-dcec-55a0-add4-380ae95768fb', 'f3c3fe51-0873-5b0c-a9e5-c98d952e8437', null, 'metodos_empregados', 'Métodos empregados na perícia', 'selecao_multipla', 1, false, true, '[{"codigo": "analise_autos", "rotulo": "Análise dos autos"}, {"codigo": "analise_documental_medica", "rotulo": "Análise documental médica"}, {"codigo": "entrevista_direta_periciando", "rotulo": "Entrevista direta com o(a) periciando(a)"}, {"codigo": "heteroanamnese", "rotulo": "Heteroanamnese"}, {"codigo": "exame_clinico_geral", "rotulo": "Exame clínico geral"}, {"codigo": "exame_neurologico_direcionado", "rotulo": "Exame neurológico direcionado"}, {"codigo": "exame_estado_mental", "rotulo": "Exame do estado mental"}, {"codigo": "avaliacao_cognitiva", "rotulo": "Avaliação cognitiva"}, {"codigo": "avaliacao_funcional", "rotulo": "Avaliação funcional"}, {"codigo": "aplicacao_escala_instrumento_padronizado", "rotulo": "Aplicação de escala/instrumento padronizado"}, {"codigo": "observacao_comportamental", "rotulo": "Observação comportamental"}, {"codigo": "outros", "rotulo": "Outros"}]'::jsonb, null, false, null, false),
  ('5032bc2e-4c2d-5d46-8480-9ffe7fcadaef', 'f3c3fe51-0873-5b0c-a9e5-c98d952e8437', null, 'instrumentos_escalas_utilizados', 'Instrumentos/escalas utilizados', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('f01450bd-605d-573b-925e-480ad28dd1e3', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'diagnostico_previamente_estabelecido', 'Diagnóstico previamente estabelecido', 'selecao_unica', 1, false, true, '[{"codigo": "sim", "rotulo": "Sim"}, {"codigo": "nao", "rotulo": "Não"}, {"codigo": "em_investigacao", "rotulo": "Em investigação"}]'::jsonb, null, false, null, false),
  ('a156a156-4ded-51e6-bc7c-78a618abdc11', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'diagnostico_informado', 'Diagnóstico informado', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('90fdc83e-8b8e-5265-ab1b-b0162fcb9c63', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'cid_condicao_principal', 'CID', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('ce46f997-bbe1-5b92-903d-2c7c203d7840', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'fonte_diagnostico', 'Fonte do diagnóstico', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('f0c299ea-b5d1-5afb-af21-68b066eb2432', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'inicio_condicao', 'Início da condição', 'selecao_multipla', 5, false, true, '[{"codigo": "congenito", "rotulo": "Congênito"}, {"codigo": "infancia", "rotulo": "Infância"}, {"codigo": "adolescencia", "rotulo": "Adolescência"}, {"codigo": "vida_adulta", "rotulo": "Vida adulta"}, {"codigo": "idoso", "rotulo": "Idoso"}, {"codigo": "subito", "rotulo": "Súbito"}, {"codigo": "insidioso", "rotulo": "Insidioso"}, {"codigo": "progressivo", "rotulo": "Progressivo"}, {"codigo": "apos_evento_neurologico", "rotulo": "Após evento neurológico"}, {"codigo": "apos_traumatismo", "rotulo": "Após traumatismo"}, {"codigo": "apos_doenca_clinica", "rotulo": "Após doença clínica"}, {"codigo": "nao_determinado", "rotulo": "Não determinado"}]'::jsonb, null, false, null, false),
  ('708ab2ba-c977-56f1-a1f4-1b017778424c', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'tempo_aproximado_evolucao', 'Tempo aproximado de evolução', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('a90a7cd4-c224-5060-abfe-759f26945b84', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'curso_clinico', 'Curso clínico', 'selecao_unica', 7, false, true, '[{"codigo": "estavel", "rotulo": "Estável"}, {"codigo": "progressivo", "rotulo": "Progressivo"}, {"codigo": "flutuante", "rotulo": "Flutuante"}, {"codigo": "episodico", "rotulo": "Episódico"}, {"codigo": "com_periodos_remissao", "rotulo": "Com períodos de remissão"}, {"codigo": "em_melhora", "rotulo": "Em melhora"}, {"codigo": "em_agravamento", "rotulo": "Em agravamento"}, {"codigo": "nao_determinado", "rotulo": "Não determinado"}]'::jsonb, null, false, null, false),
  ('74f38e87-aa3f-5ace-b8ff-d66514ae7cc1', '2b3ffd99-d5fc-5062-bc5c-e7ce04619a8d', null, 'manifestacoes_predominantes', 'Manifestações predominantes', 'selecao_multipla', 8, false, true, '[{"codigo": "deficit_memoria", "rotulo": "Déficit de memória"}, {"codigo": "desorientacao", "rotulo": "Desorientação"}, {"codigo": "alteracao_comportamento", "rotulo": "Alteração de comportamento"}, {"codigo": "alteracao_personalidade", "rotulo": "Alteração de personalidade"}, {"codigo": "prejuizo_intelectual", "rotulo": "Prejuízo intelectual"}, {"codigo": "delirios", "rotulo": "Delírios"}, {"codigo": "alucinacoes", "rotulo": "Alucinações"}, {"codigo": "desorganizacao_pensamento", "rotulo": "Desorganização do pensamento"}, {"codigo": "impulsividade", "rotulo": "Impulsividade"}, {"codigo": "alteracao_linguagem", "rotulo": "Alteração de linguagem"}, {"codigo": "deficit_executivo", "rotulo": "Déficit executivo"}, {"codigo": "limitacao_motora", "rotulo": "Limitação motora"}, {"codigo": "dependencia_funcional", "rotulo": "Dependência funcional"}, {"codigo": "outras", "rotulo": "Outras"}]'::jsonb, null, false, null, false),
  ('18501117-dc8a-5f5c-8190-93d00c35d240', '2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', null, 'antecedentes_relevantes', 'Antecedentes relevantes', 'selecao_multipla', 1, false, true, '[{"codigo": "deficiencia_intelectual", "rotulo": "Deficiência intelectual"}, {"codigo": "tea", "rotulo": "Transtorno do espectro autista"}, {"codigo": "transtorno_psicotico", "rotulo": "Transtorno psicótico"}, {"codigo": "transtorno_humor", "rotulo": "Transtorno do humor"}, {"codigo": "demencia", "rotulo": "Demência"}, {"codigo": "alzheimer", "rotulo": "Doença de Alzheimer"}, {"codigo": "parkinson", "rotulo": "Doença de Parkinson"}, {"codigo": "avc", "rotulo": "AVC"}, {"codigo": "tce", "rotulo": "Traumatismo cranioencefálico"}, {"codigo": "epilepsia", "rotulo": "Epilepsia"}, {"codigo": "doenca_neurologica", "rotulo": "Doença neurológica"}, {"codigo": "dependencia_alcool", "rotulo": "Dependência de álcool"}, {"codigo": "uso_substancias_psicoativas", "rotulo": "Uso de substâncias psicoativas"}, {"codigo": "internacao_psiquiatrica_previa", "rotulo": "Internação psiquiátrica prévia"}, {"codigo": "outras_doencas_clinicas_relevantes", "rotulo": "Outras doenças clínicas relevantes"}, {"codigo": "sem_antecedentes_relevantes", "rotulo": "Sem antecedentes relevantes conhecidos"}]'::jsonb, null, false, null, false),
  ('50370535-d9d0-50e0-a7c4-c550041d00a8', '2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', null, 'descricao_antecedentes', 'Descrição', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('d8d3fe2a-4133-525a-ac29-3a5262d9781a', '2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', null, 'tratamento_atual', 'Tratamento atual', 'selecao_multipla', 3, false, true, '[{"codigo": "psiquiatria", "rotulo": "Psiquiatria"}, {"codigo": "neurologia", "rotulo": "Neurologia"}, {"codigo": "geriatria", "rotulo": "Geriatria"}, {"codigo": "clinica_medica", "rotulo": "Clínica médica"}, {"codigo": "psicologia", "rotulo": "Psicologia"}, {"codigo": "terapia_ocupacional", "rotulo": "Terapia ocupacional"}, {"codigo": "fonoaudiologia", "rotulo": "Fonoaudiologia"}, {"codigo": "fisioterapia", "rotulo": "Fisioterapia"}, {"codigo": "caps", "rotulo": "CAPS"}, {"codigo": "cuidador_formal", "rotulo": "Cuidador formal"}, {"codigo": "cuidador_familiar", "rotulo": "Cuidador familiar"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('e2dc1f74-ac7d-52de-893d-72dda82c299a', '2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', null, 'medicacoes_em_uso', 'Medicações em uso', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('eee33ac3-3b6f-5169-bce2-370ffca3b53d', '2d4791fb-e27d-5fb4-ba71-573ca97ebcf1', null, 'adesao_terapeutica', 'Adesão terapêutica', 'selecao_unica', 5, false, true, '[{"codigo": "autonoma_adequada", "rotulo": "Autônoma e adequada"}, {"codigo": "necessita_lembretes", "rotulo": "Necessita lembretes"}, {"codigo": "necessita_supervisao", "rotulo": "Necessita supervisão"}, {"codigo": "medicacao_administrada_por_terceiros", "rotulo": "Medicação administrada integralmente por terceiros"}, {"codigo": "irregular", "rotulo": "Irregular"}, {"codigo": "nao_foi_possivel_avaliar", "rotulo": "Não foi possível avaliar"}]'::jsonb, null, false, null, false),
  ('494ae0d8-1a3e-55eb-bd88-15f94e3a8be0', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'estado_geral', 'Estado geral', 'selecao_unica', 1, false, true, '[{"codigo": "bom", "rotulo": "Bom"}, {"codigo": "regular", "rotulo": "Regular"}, {"codigo": "comprometido", "rotulo": "Comprometido"}]'::jsonb, null, false, null, false),
  ('ae5773f7-b527-57a1-a81f-882fd38a2766', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'apresentacao_pessoal', 'Apresentação pessoal', 'selecao_unica', 2, false, true, '[{"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "parcialmente_adequada", "rotulo": "Parcialmente adequada"}, {"codigo": "inadequada", "rotulo": "Inadequada"}]'::jsonb, null, false, null, false),
  ('0244dfb0-48a1-54fc-9cc5-274af7187a86', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'higiene', 'Higiene', 'selecao_unica', 3, false, true, '[{"codigo": "preservada_autonomamente", "rotulo": "Preservada autonomamente"}, {"codigo": "preservada_com_auxilio", "rotulo": "Preservada com auxílio"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}]'::jsonb, null, false, null, false),
  ('00406a17-e4f3-5823-92ba-8153bae7b589', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'nutricao', 'Nutrição', 'selecao_unica', 4, false, true, '[{"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "alterada", "rotulo": "Alterada"}, {"codigo": "nao_avaliada", "rotulo": "Não avaliada"}]'::jsonb, null, false, null, false),
  ('9a24a5f8-6122-5c74-8c3c-448163cd226d', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'locomocao', 'Locomoção', 'selecao_unica', 5, false, true, '[{"codigo": "independente", "rotulo": "Independente"}, {"codigo": "com_auxilio_terceiro", "rotulo": "Com auxílio de terceiro"}, {"codigo": "bengala", "rotulo": "Bengala"}, {"codigo": "andador", "rotulo": "Andador"}, {"codigo": "cadeira_rodas", "rotulo": "Cadeira de rodas"}, {"codigo": "restrito_ao_leito", "rotulo": "Restrito(a) ao leito"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('e683ef28-7665-5f99-93d0-9a1a42c8630c', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'comunicacao', 'Comunicação', 'selecao_unica', 6, false, true, '[{"codigo": "plenamente_funcional", "rotulo": "Plenamente funcional"}, {"codigo": "funcional_com_limitacoes", "rotulo": "Funcional com limitações"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "ausente_verbalmente", "rotulo": "Ausente verbalmente"}, {"codigo": "comunicacao_alternativa", "rotulo": "Comunicação alternativa"}]'::jsonb, null, false, null, false),
  ('3395e5e2-e6ce-545a-a526-215dc8a84c9f', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'deficits_sensoriais_relevantes', 'Déficits sensoriais relevantes', 'selecao_unica', 7, false, true, '[{"codigo": "ausentes", "rotulo": "Ausentes"}, {"codigo": "visual", "rotulo": "Visual"}, {"codigo": "auditivo", "rotulo": "Auditivo"}, {"codigo": "ambos", "rotulo": "Ambos"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('728ae3b5-cc14-5085-8ae7-15ca510f15e6', '27fbf857-417c-5198-894f-cb2b70abc9ea', null, 'cooperacao_exame', 'Cooperação com o exame', 'selecao_unica', 8, false, true, '[{"codigo": "plena", "rotulo": "Plena"}, {"codigo": "parcial", "rotulo": "Parcial"}, {"codigo": "reduzida", "rotulo": "Reduzida"}, {"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "nao_compreende_solicitacoes", "rotulo": "Não compreende suficientemente as solicitações"}]'::jsonb, null, false, null, false),
  ('688ae7d2-e36e-54b5-8118-88c7b8bee0a5', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'consciencia', 'Consciência', 'selecao_unica', 1, false, true, '[{"codigo": "lucido", "rotulo": "Lúcido(a)"}, {"codigo": "sonolento", "rotulo": "Sonolento(a)"}, {"codigo": "obnubilado", "rotulo": "Obnubilado(a)"}, {"codigo": "torporoso", "rotulo": "Torporoso(a)"}, {"codigo": "outro", "rotulo": "Outro"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('8c73e7f6-548f-507f-bf56-58411b775036', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'orientacao_autopsiquica', 'Orientação autopsíquica', 'selecao_unica', 2, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "parcialmente_prejudicada", "rotulo": "Parcialmente prejudicada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('463fa666-bbcc-55ac-b705-3d86c862dca9', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'orientacao_temporal', 'Orientação temporal', 'selecao_unica', 3, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "parcialmente_prejudicada", "rotulo": "Parcialmente prejudicada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('9906492e-7f91-5bfd-9f2a-80ac0a5dff0a', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'orientacao_espacial', 'Orientação espacial', 'selecao_unica', 4, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "parcialmente_prejudicada", "rotulo": "Parcialmente prejudicada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('103fe916-1fac-5be0-92c0-b3e96fc41cf1', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'orientacao_situacional', 'Orientação situacional', 'selecao_unica', 5, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "parcialmente_prejudicada", "rotulo": "Parcialmente prejudicada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('e64c18cb-24e7-5684-9282-90d964ce9399', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'atencao_concentracao', 'Atenção e concentração', 'selecao_unica', 6, false, true, '[{"codigo": "preservadas", "rotulo": "Preservadas"}, {"codigo": "discretamente_prejudicadas", "rotulo": "Discretamente prejudicadas"}, {"codigo": "moderadamente_prejudicadas", "rotulo": "Moderadamente prejudicadas"}, {"codigo": "gravemente_prejudicadas", "rotulo": "Gravemente prejudicadas"}, {"codigo": "flutuantes", "rotulo": "Flutuantes"}, {"codigo": "nao_avaliaveis", "rotulo": "Não avaliáveis"}]'::jsonb, null, false, null, false),
  ('28ec6abd-b7dd-51b8-ad7b-f9e615692c18', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'memoria_imediata', 'Memória imediata', 'selecao_unica', 7, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "discretamente_prejudicada", "rotulo": "Discretamente prejudicada"}, {"codigo": "moderadamente_prejudicada", "rotulo": "Moderadamente prejudicada"}, {"codigo": "gravemente_prejudicada", "rotulo": "Gravemente prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('41b1a9d7-9a30-50dc-a721-8dd3ae24ff04', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'memoria_recente', 'Memória recente', 'selecao_unica', 8, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "discretamente_prejudicada", "rotulo": "Discretamente prejudicada"}, {"codigo": "moderadamente_prejudicada", "rotulo": "Moderadamente prejudicada"}, {"codigo": "gravemente_prejudicada", "rotulo": "Gravemente prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('0934f315-151a-58b9-9962-ee8b075e5433', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'memoria_remota', 'Memória remota', 'selecao_unica', 9, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "discretamente_prejudicada", "rotulo": "Discretamente prejudicada"}, {"codigo": "moderadamente_prejudicada", "rotulo": "Moderadamente prejudicada"}, {"codigo": "gravemente_prejudicada", "rotulo": "Gravemente prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('56a8f331-1e5c-5b46-a9fa-7f610bbc0458', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'linguagem', 'Linguagem', 'selecao_unica', 10, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "empobrecida", "rotulo": "Empobrecida"}, {"codigo": "disartrica", "rotulo": "Disártrica"}, {"codigo": "disfasica", "rotulo": "Disfásica"}, {"codigo": "afasica", "rotulo": "Afásica"}, {"codigo": "perseverativa", "rotulo": "Perseverativa"}, {"codigo": "incoerente", "rotulo": "Incoerente"}, {"codigo": "comunicacao_limitada", "rotulo": "Comunicação limitada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('6d6459c5-3e12-5cf9-8f70-69597f06e207', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'pensamento_curso', 'Pensamento — curso', 'selecao_unica', 11, false, true, '[{"codigo": "regular", "rotulo": "Regular"}, {"codigo": "lentificado_bradipsiquico", "rotulo": "Lentificado/bradipsíquico"}, {"codigo": "acelerado_taquipsiquico", "rotulo": "Acelerado/taquipsíquico"}, {"codigo": "prolixo", "rotulo": "Prolixo"}, {"codigo": "circunstancial", "rotulo": "Circunstancial"}, {"codigo": "tangencial", "rotulo": "Tangencial"}, {"codigo": "com_bloqueios", "rotulo": "Com bloqueios"}, {"codigo": "desorganizado", "rotulo": "Desorganizado"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('3e4f7d5b-e97e-5aca-81ec-1ff1f9cf2c0f', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'pensamento_forma', 'Pensamento — forma', 'selecao_unica', 12, false, true, '[{"codigo": "organizada", "rotulo": "Organizada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "desagregada", "rotulo": "Desagregada"}, {"codigo": "incoerente", "rotulo": "Incoerente"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('36804370-08b4-51da-a6e6-b998edb120f6', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'pensamento_conteudo', 'Pensamento — conteúdo', 'selecao_multipla', 13, false, true, '[{"codigo": "sem_alteracoes_relevantes", "rotulo": "Sem alterações relevantes"}, {"codigo": "delirante", "rotulo": "Delirante"}, {"codigo": "persecutorio", "rotulo": "Persecutório"}, {"codigo": "grandioso", "rotulo": "Grandioso"}, {"codigo": "mistico_religioso_patologico", "rotulo": "Místico/religioso patológico"}, {"codigo": "hipocondriaco", "rotulo": "Hipocondríaco"}, {"codigo": "obsessivo", "rotulo": "Obsessivo"}, {"codigo": "ideacao_suicida", "rotulo": "Ideação suicida"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('cbf3c63a-cff3-5297-acab-6066e3a0a35a', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'sensopercepcao', 'Sensopercepção', 'selecao_multipla', 14, false, true, '[{"codigo": "sem_alteracoes_evidenciadas", "rotulo": "Sem alterações evidenciadas"}, {"codigo": "alucinacoes_auditivas", "rotulo": "Alucinações auditivas"}, {"codigo": "alucinacoes_visuais", "rotulo": "Alucinações visuais"}, {"codigo": "outras_alteracoes", "rotulo": "Outras alterações"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('ef2da2f5-64b8-5c56-8fb5-4b7d8da379ca', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'humor', 'Humor', 'selecao_unica', 15, false, true, '[{"codigo": "eutimico", "rotulo": "Eutímico"}, {"codigo": "deprimido", "rotulo": "Deprimido"}, {"codigo": "elevado", "rotulo": "Elevado"}, {"codigo": "irritavel", "rotulo": "Irritável"}, {"codigo": "ansioso", "rotulo": "Ansioso"}, {"codigo": "labil", "rotulo": "Lábil"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('e1935169-67ff-53d3-8d1f-a1db83a83665', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'afeto', 'Afeto', 'selecao_unica', 16, false, true, '[{"codigo": "adequado", "rotulo": "Adequado"}, {"codigo": "hipomodulado", "rotulo": "Hipomodulado"}, {"codigo": "embotado", "rotulo": "Embotado"}, {"codigo": "labil", "rotulo": "Lábil"}, {"codigo": "incongruente", "rotulo": "Incongruente"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('6b89467d-6870-5e18-9fff-9eec7cf28a31', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'psicomotricidade', 'Psicomotricidade', 'selecao_unica', 17, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "lentificada", "rotulo": "Lentificada"}, {"codigo": "agitada", "rotulo": "Agitada"}, {"codigo": "inquieta", "rotulo": "Inquieta"}, {"codigo": "estereotipada", "rotulo": "Estereotipada"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('c2aba3f2-474a-5e4b-ad64-f21a650495e7', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'capacidade_abstracao', 'Capacidade de abstração', 'selecao_unica', 18, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "parcialmente_prejudicada", "rotulo": "Parcialmente prejudicada"}, {"codigo": "prejudicada", "rotulo": "Prejudicada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('1193c43e-e691-59de-8f76-0123332717c5', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'funcao_executiva_planejamento', 'Funções executivas — planejamento', 'selecao_unica', 19, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "comprometido", "rotulo": "Comprometido"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('88a9b5d4-ee43-53bc-91d2-a5998b1ce25e', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'funcao_executiva_organizacao', 'Funções executivas — organização', 'selecao_unica', 20, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "comprometido", "rotulo": "Comprometido"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('e0a90129-c12b-5657-838b-9d6aaf0bf562', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'funcao_executiva_resolucao_problemas', 'Funções executivas — resolução de problemas', 'selecao_unica', 21, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "comprometido", "rotulo": "Comprometido"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('8afb8f6b-6983-5f70-b1d2-f71d4f5e1df5', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'funcao_executiva_flexibilidade_cognitiva', 'Funções executivas — flexibilidade cognitiva', 'selecao_unica', 22, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "comprometido", "rotulo": "Comprometido"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('b91ae35a-80d0-5668-8bbc-bb63ee2a759e', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'juizo_critico', 'Juízo crítico', 'selecao_unica', 23, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "gravemente_comprometido", "rotulo": "Gravemente comprometido"}, {"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('038d7057-242c-5eb5-b96d-46f569c2e48a', '2c2d3d72-c0c3-5846-9f38-37978db3e408', null, 'insight', 'Insight', 'selecao_unica', 24, false, true, '[{"codigo": "preservado", "rotulo": "Preservado"}, {"codigo": "parcial", "rotulo": "Parcial"}, {"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('a0f58655-434c-5213-8839-f705bc2e6603', 'f3c251ab-d2ce-5696-89d4-06a3f15f8c9c', null, 'teste_aplicado', 'Teste aplicado', 'selecao_unica', 1, false, true, '[{"codigo": "meem", "rotulo": "Mini Exame do Estado Mental — MEEM"}, {"codigo": "moca", "rotulo": "MoCA"}, {"codigo": "teste_relogio", "rotulo": "Teste do Relógio"}, {"codigo": "fluencia_verbal", "rotulo": "Fluência verbal"}, {"codigo": "outro", "rotulo": "Outro"}, {"codigo": "nao_aplicado", "rotulo": "Não aplicado"}]'::jsonb, null, false, null, false),
  ('310c725c-e98d-5b2d-b697-ce3ffec9f16b', 'f3c251ab-d2ce-5696-89d4-06a3f15f8c9c', null, 'pontuacao_teste_cognitivo', 'Pontuação', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('5c3259ea-4486-5889-9ab6-c1b65caa784d', 'f3c251ab-d2ce-5696-89d4-06a3f15f8c9c', null, 'escolaridade_considerada_teste', 'Escolaridade considerada', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('d3d1814f-1162-50e5-b594-0522b59c99ef', 'f3c251ab-d2ce-5696-89d4-06a3f15f8c9c', null, 'interpretacao_teste_cognitivo', 'Interpretação', 'selecao_unica', 4, false, true, '[{"codigo": "dentro_esperado", "rotulo": "Dentro do esperado"}, {"codigo": "alteracao_leve", "rotulo": "Alteração leve"}, {"codigo": "alteracao_moderada", "rotulo": "Alteração moderada"}, {"codigo": "alteracao_importante", "rotulo": "Alteração importante"}, {"codigo": "resultado_inconclusivo", "rotulo": "Resultado inconclusivo"}, {"codigo": "interpretacao_prejudicada", "rotulo": "Interpretação prejudicada"}]'::jsonb, null, false, null, false),
  ('0a96bf5c-694a-5bf1-9f57-f6a46c45b128', '647490b9-ed73-511f-8f3f-b6ca2a4dc76c', null, 'avaliacao_funcional_abvd', 'Atividades básicas da vida diária', 'tabela', 1, false, true, null, '{"linhas": [{"codigo": "alimentar_se", "rotulo": "Alimentar-se"}, {"codigo": "banhar_se", "rotulo": "Banhar-se"}, {"codigo": "vestir_se", "rotulo": "Vestir-se"}, {"codigo": "higiene_pessoal", "rotulo": "Higiene pessoal"}, {"codigo": "uso_sanitario", "rotulo": "Uso do sanitário"}, {"codigo": "mobilidade", "rotulo": "Mobilidade"}], "colunas": [{"codigo": "nivel", "rotulo": "Nível de dependência", "opcoes": [{"codigo": "0", "rotulo": "Independente"}, {"codigo": "1", "rotulo": "Necessita supervisão/lembretes"}, {"codigo": "2", "rotulo": "Necessita auxílio parcial"}, {"codigo": "3", "rotulo": "Dependente de terceiros"}, {"codigo": "NA", "rotulo": "Não avaliável/não aplicável"}]}]}'::jsonb, false, null, false),
  ('5ad8627b-7701-58b2-9b8d-7f1eea4c4ba0', '647490b9-ed73-511f-8f3f-b6ca2a4dc76c', null, 'avaliacao_funcional_aivd', 'Atividades instrumentais', 'tabela', 2, false, true, null, '{"linhas": [{"codigo": "preparar_alimentacao", "rotulo": "Preparar alimentação"}, {"codigo": "utilizar_telefone", "rotulo": "Utilizar telefone"}, {"codigo": "utilizar_transporte", "rotulo": "Utilizar transporte"}, {"codigo": "realizar_compras", "rotulo": "Realizar compras"}, {"codigo": "organizar_medicamentos", "rotulo": "Organizar medicamentos"}, {"codigo": "administrar_rotina", "rotulo": "Administrar rotina"}, {"codigo": "realizar_pagamentos", "rotulo": "Realizar pagamentos"}, {"codigo": "utilizar_servicos_bancarios", "rotulo": "Utilizar serviços bancários"}], "colunas": [{"codigo": "nivel", "rotulo": "Nível de dependência", "opcoes": [{"codigo": "0", "rotulo": "Independente"}, {"codigo": "1", "rotulo": "Necessita supervisão/lembretes"}, {"codigo": "2", "rotulo": "Necessita auxílio parcial"}, {"codigo": "3", "rotulo": "Dependente de terceiros"}, {"codigo": "NA", "rotulo": "Não avaliável/não aplicável"}]}]}'::jsonb, false, null, false),
  ('e61fc4bd-4f6f-5dbb-bc3e-8f62e0b50e7c', '0188ba27-cec7-586d-97e6-2f4b67ae8af7', null, 'avaliacao_capacidade_civil_discernimento', 'Avaliação específica da capacidade civil e do discernimento', 'tabela', 1, false, true, null, '{"linhas": [{"codigo": "compreender_informacoes_simples", "rotulo": "Compreender informações simples"}, {"codigo": "compreender_informacoes_complexas", "rotulo": "Compreender informações complexas"}, {"codigo": "compreender_natureza_decisao", "rotulo": "Compreender natureza de uma decisão"}, {"codigo": "compreender_consequencias_previsiveis", "rotulo": "Compreender consequências previsíveis"}, {"codigo": "comparar_alternativas", "rotulo": "Comparar alternativas"}, {"codigo": "raciocinar_riscos_beneficios", "rotulo": "Raciocinar sobre riscos e benefícios"}, {"codigo": "formar_decisao_propria", "rotulo": "Formar decisão própria"}, {"codigo": "expressar_escolha", "rotulo": "Expressar escolha"}, {"codigo": "manter_escolha_consistente", "rotulo": "Manter escolha de forma consistente"}, {"codigo": "reconhecer_situacoes_risco", "rotulo": "Reconhecer situações de risco"}, {"codigo": "reconhecer_fraude_abuso_financeiro", "rotulo": "Reconhecer fraude/abuso financeiro"}, {"codigo": "administrar_valores_cotidianos", "rotulo": "Administrar valores cotidianos"}, {"codigo": "administrar_patrimonio_relevante", "rotulo": "Administrar patrimônio relevante"}, {"codigo": "compreender_operacoes_bancarias", "rotulo": "Compreender operações bancárias"}, {"codigo": "compreender_contratos_negocios", "rotulo": "Compreender contratos/negócios"}, {"codigo": "manifestar_preferencias_pessoais", "rotulo": "Manifestar preferências pessoais"}, {"codigo": "solicitar_auxilio_quando_necessario", "rotulo": "Solicitar auxílio quando necessário"}], "colunas": [{"codigo": "grau", "rotulo": "Grau de preservação", "opcoes": [{"codigo": "P", "rotulo": "Preservada"}, {"codigo": "PC", "rotulo": "Parcialmente comprometida"}, {"codigo": "C", "rotulo": "Comprometida"}, {"codigo": "NA", "rotulo": "Não avaliável"}]}]}'::jsonb, false, null, false),
  ('42e64ca2-9695-5a7d-b088-4080a3d1fa20', '651f303d-e9d1-55b2-9357-f1d63e642bf8', null, 'manifestacao_vontade', 'Manifestação da vontade', 'selecao_unica', 1, false, true, '[{"codigo": "clara_livre_consistente", "rotulo": "Clara, livre e consistente"}, {"codigo": "preservada_decisoes_simples", "rotulo": "Preservada para decisões simples"}, {"codigo": "necessita_facilitacao", "rotulo": "Necessita facilitação para compreender opções"}, {"codigo": "oscilante_inconsistente", "rotulo": "Oscilante/inconsistente"}, {"codigo": "significativamente_prejudicada", "rotulo": "Significativamente prejudicada"}, {"codigo": "nao_foi_possivel_aferir", "rotulo": "Não foi possível aferir"}]'::jsonb, null, false, null, false),
  ('907875f0-ed93-5e7b-87c1-a2af018a17e4', '651f303d-e9d1-55b2-9357-f1d63e642bf8', null, 'suscetibilidade_influencia_indevida', 'Suscetibilidade à influência indevida', 'selecao_unica', 2, false, true, '[{"codigo": "nao_evidenciada", "rotulo": "Não evidenciada"}, {"codigo": "baixa", "rotulo": "Baixa"}, {"codigo": "moderada", "rotulo": "Moderada"}, {"codigo": "elevada", "rotulo": "Elevada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('d0957743-4d5c-5bfb-97fb-71f8480b46f0', '651f303d-e9d1-55b2-9357-f1d63e642bf8', null, 'necessidade_global_apoio', 'Necessidade global de apoio', 'selecao_unica', 3, false, true, '[{"codigo": "nao_necessita", "rotulo": "Não necessita"}, {"codigo": "apoio_pontual", "rotulo": "Apoio pontual"}, {"codigo": "supervisao_atividades_determinadas", "rotulo": "Supervisão para determinadas atividades"}, {"codigo": "auxilio_frequente", "rotulo": "Auxílio frequente"}, {"codigo": "auxilio_continuo", "rotulo": "Auxílio contínuo"}, {"codigo": "substituicao_terceiro_atos_patrimoniais", "rotulo": "Substituição por terceiro em determinados atos patrimoniais/negociais"}]'::jsonb, null, false, null, false),
  ('27873ca7-d90c-51e5-be5e-0b406749e5bb', '651f303d-e9d1-55b2-9357-f1d63e642bf8', null, 'dominios_necessita_apoio', 'Domínios em que necessita apoio', 'selecao_multipla', 4, false, true, '[{"codigo": "gestao_financeira_cotidiana", "rotulo": "Gestão financeira cotidiana"}, {"codigo": "movimentacao_bancaria", "rotulo": "Movimentação bancária"}, {"codigo": "administracao_patrimonial", "rotulo": "Administração patrimonial"}, {"codigo": "contratos", "rotulo": "Contratos"}, {"codigo": "compra_venda_bens", "rotulo": "Compra/venda de bens"}, {"codigo": "emprestimos_financiamentos", "rotulo": "Empréstimos/financiamentos"}, {"codigo": "doacoes", "rotulo": "Doações"}, {"codigo": "outros_atos_negociais", "rotulo": "Outros atos negociais"}, {"codigo": "organizacao_terapeutica", "rotulo": "Organização terapêutica"}, {"codigo": "outros", "rotulo": "Outros"}]'::jsonb, null, false, null, false),
  ('1ed4f700-844e-5258-8fa0-82d0c3f3403b', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'diagnostico_principal', 'Diagnóstico principal', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('42d4b3e1-8f14-58c0-90ce-80ee94d1eb80', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'cid_diagnostico_principal', 'CID', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('c5e38806-72ce-5810-9cd0-5070ba8d3d31', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'diagnosticos_associados', 'Diagnósticos associados', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('80c20af0-c6d8-5d91-b32f-7a317b3f1061', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'natureza_condicao', 'Natureza', 'selecao_multipla', 4, false, true, '[{"codigo": "congenita", "rotulo": "Congênita"}, {"codigo": "adquirida", "rotulo": "Adquirida"}, {"codigo": "neurologica", "rotulo": "Neurológica"}, {"codigo": "psiquiatrica", "rotulo": "Psiquiátrica"}, {"codigo": "neurodegenerativa", "rotulo": "Neurodegenerativa"}, {"codigo": "intelectual", "rotulo": "Intelectual"}, {"codigo": "multifatorial", "rotulo": "Multifatorial"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('6602e0c7-f9d5-58de-b90f-691e2b9f6ada', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'prognostico_clinico', 'Prognóstico clínico', 'selecao_unica', 5, false, true, '[{"codigo": "favoravel", "rotulo": "Favorável"}, {"codigo": "reservado", "rotulo": "Reservado"}, {"codigo": "desfavoravel", "rotulo": "Desfavorável"}, {"codigo": "indeterminado", "rotulo": "Indeterminado"}]'::jsonb, null, false, null, false),
  ('4d5f4a4f-66a4-58d2-9c43-4a8690a99750', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'evolucao_esperada', 'Evolução esperada', 'selecao_unica', 6, false, true, '[{"codigo": "reversivel", "rotulo": "Reversível"}, {"codigo": "potencialmente_reversivel", "rotulo": "Potencialmente reversível"}, {"codigo": "estavel", "rotulo": "Estável"}, {"codigo": "progressiva", "rotulo": "Progressiva"}, {"codigo": "irreversivel", "rotulo": "Irreversível"}, {"codigo": "indeterminada", "rotulo": "Indeterminada"}]'::jsonb, null, false, null, false),
  ('05008102-8990-5a2f-a76d-924be86faaf2', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'duracao_repercussoes_funcionais', 'Duração provável das repercussões funcionais', 'selecao_unica', 7, false, true, '[{"codigo": "transitoria", "rotulo": "Transitória"}, {"codigo": "prolongada", "rotulo": "Prolongada"}, {"codigo": "permanente", "rotulo": "Permanente"}, {"codigo": "indeterminada", "rotulo": "Indeterminada"}]'::jsonb, null, false, null, false),
  ('b8b0ec26-2e21-57bb-b9bb-0e892f619ada', '7fabc9e8-8e47-5e80-9095-8393626f935f', null, 'possibilidade_reavaliacao_futura', 'Possibilidade de reavaliação futura', 'selecao_unica', 8, false, true, '[{"codigo": "recomendada", "rotulo": "Recomendada"}, {"codigo": "nao_ha_indicacao_clinica_atual", "rotulo": "Não há indicação clínica atual"}, {"codigo": "conforme_evolucao_terapeutica", "rotulo": "Conforme evolução terapêutica"}, {"codigo": "em_aproximadamente", "rotulo": "Em aproximadamente (meses/anos)"}]'::jsonb, null, false, null, false),
  ('63742bee-55e9-5618-84b9-3e6dd0b264ed', 'ff1784c0-5149-5836-a94b-9bea1d7cd633', null, 'discussao_medico_legal_texto', 'Discussão médico-legal', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('7c47aa5f-be72-5aa1-bfa5-8b5b3f85bfab', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'apresenta_condicao_capaz_repercutir', '1. Apresenta condição clínica capaz de repercutir sobre sua capacidade civil?', 'selecao_unica', 1, false, true, '[{"codigo": "nao", "rotulo": "Não"}, {"codigo": "sim", "rotulo": "Sim"}, {"codigo": "parcial_inconclusivo", "rotulo": "Parcialmente/inconclusivo — necessita complementação"}]'::jsonb, null, false, null, true),
  ('4b1b543d-1157-57fa-b9e7-94e1dc9f3287', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_diagnostico', 'Diagnóstico', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('6a5c6759-e7d9-55b6-84b4-76d121bd0a51', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_cid', 'CID', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('142c776b-a1da-55f2-81b2-885d04954677', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_discernimento', '2. Discernimento', 'selecao_unica', 4, false, true, '[{"codigo": "globalmente_preservado", "rotulo": "Globalmente preservado"}, {"codigo": "parcialmente_comprometido", "rotulo": "Parcialmente comprometido"}, {"codigo": "significativamente_comprometido", "rotulo": "Significativamente comprometido"}, {"codigo": "nao_avaliavel_de_forma_conclusiva", "rotulo": "Não avaliável de forma conclusiva"}]'::jsonb, null, false, null, false),
  ('2eeaabe1-d13e-5d82-a83d-c3d4499e4bf9', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_capacidade_manifestacao_vontade', '3. Capacidade de manifestação da vontade', 'selecao_unica', 5, false, true, '[{"codigo": "preservada", "rotulo": "Preservada"}, {"codigo": "preservada_com_necessidade_apoio", "rotulo": "Preservada com necessidade de apoio"}, {"codigo": "parcialmente_comprometida", "rotulo": "Parcialmente comprometida"}, {"codigo": "significativamente_comprometida", "rotulo": "Significativamente comprometida"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('522ac68a-a085-5da6-963c-3717c3a40445', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_repercussao_atos_patrimoniais', '4. Repercussão sobre atos patrimoniais e negociais', 'selecao_unica', 6, false, true, '[{"codigo": "nao_ha_comprometimento_demonstravel", "rotulo": "Não há comprometimento médico-pericial demonstrável"}, {"codigo": "comprometimento_limitado_maior_complexidade", "rotulo": "Comprometimento limitado a atos de maior complexidade"}, {"codigo": "comprometimento_relevante", "rotulo": "Comprometimento relevante"}, {"codigo": "comprometimento_grave_generalizado", "rotulo": "Comprometimento grave/generalizado"}, {"codigo": "nao_foi_possivel_concluir", "rotulo": "Não foi possível concluir"}]'::jsonb, null, false, null, false),
  ('65edcb52-4ada-5407-9d7a-45c57088a265', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_necessidade_apoio_protecao', '5. Necessidade médico-pericial de apoio/proteção', 'selecao_unica', 7, false, true, '[{"codigo": "nao_identificada", "rotulo": "Não identificada"}, {"codigo": "apoio_pontual", "rotulo": "Apoio pontual"}, {"codigo": "apoio_atos_especificos", "rotulo": "Apoio para atos específicos"}, {"codigo": "apoio_continuo_atos_patrimoniais", "rotulo": "Apoio contínuo para atos patrimoniais/negociais"}, {"codigo": "outra_medida_individualizada_juizo", "rotulo": "Outra medida a ser individualizada pelo Juízo"}]'::jsonb, null, false, null, false),
  ('4c7ddbff-64e9-57ec-b782-cdbe2028171c', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_prognostico', '6. Prognóstico', 'selecao_unica', 8, false, true, '[{"codigo": "reversivel", "rotulo": "Reversível"}, {"codigo": "potencialmente_reversivel", "rotulo": "Potencialmente reversível"}, {"codigo": "estavel", "rotulo": "Estável"}, {"codigo": "progressivo", "rotulo": "Progressivo"}, {"codigo": "irreversivel", "rotulo": "Irreversível"}, {"codigo": "indeterminado", "rotulo": "Indeterminado"}]'::jsonb, null, false, null, false),
  ('1e053b2c-635c-5862-9712-d6d174d1c7d4', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_reavaliacao', '7. Reavaliação', 'selecao_unica', 9, false, true, '[{"codigo": "nao_indicada_atualmente", "rotulo": "Não indicada atualmente"}, {"codigo": "indicada_conforme_evolucao_clinica", "rotulo": "Indicada conforme evolução clínica"}, {"codigo": "recomendada_em_prazo", "rotulo": "Recomendada em (meses/anos)"}]'::jsonb, null, false, null, false),
  ('4d18b3ae-374e-5544-9cd5-43073c2c3207', 'da60ed75-515d-58cc-b49e-329695df54d1', null, 'conclusao_modelo_automatico', 'Modelo automático de conclusão', 'selecao_unica', 10, false, true, '[{"codigo": "capacidade_preservada", "rotulo": "Capacidade preservada", "texto_automatico": "Diante dos elementos médico-periciais obtidos, não foram identificadas alterações clínicas, cognitivas ou funcionais de magnitude suficiente para comprometer significativamente a capacidade do(a) periciando(a) de compreender, deliberar e manifestar sua vontade em relação aos atos avaliados, não se evidenciando, sob a perspectiva médico-pericial, necessidade atual de representação ou assistência contínua para atos patrimoniais e negociais."}, {"codigo": "comprometimento_parcial_setorial", "rotulo": "Comprometimento parcial/setorial", "texto_automatico": "O(a) periciando(a) apresenta {{diagnostico_principal}}, com repercussão sobre [funcoes_comprometidas]. Mantém capacidade para [dominios_preservados], porém apresenta prejuízo relevante para [dominios_comprometidos], especialmente quanto a [atos_afetados]. Sob a perspectiva médico-pericial, necessita de apoio/assistência para esses atos específicos, devendo ser preservada sua autonomia nos demais domínios em que demonstra compreensão, discernimento e capacidade de manifestação da vontade."}, {"codigo": "comprometimento_acentuado", "rotulo": "Comprometimento acentuado", "texto_automatico": "O(a) periciando(a) apresenta {{diagnostico_principal}}, associado a comprometimento significativo de [funcoes_comprometidas], com repercussão relevante sobre a capacidade de compreender informações, avaliar consequências, deliberar e administrar autonomamente atos de natureza patrimonial e negocial. Sob a perspectiva médico-pericial, evidencia-se necessidade contínua de proteção e auxílio de terceiros nesses domínios, preservando-se, sempre que possível, sua participação nas decisões e a manifestação de suas preferências e vontade."}, {"codigo": "inconclusivo", "rotulo": "Inconclusivo", "texto_automatico": "Os elementos atualmente disponíveis não permitem estabelecer, com segurança médico-pericial suficiente, a extensão da repercussão da condição clínica sobre a capacidade civil do(a) periciando(a), sendo necessária complementação por [tipo_complementacao_necessaria] antes da emissão de conclusão definitiva."}]'::jsonb, null, false, null, true),
  ('7b9d8c1a-8c23-5ce7-84ca-e4071d37e7d3', '60a2b5cb-f4b3-5aec-9931-c6d2c2e5f917', null, 'cidade_uf_assinatura', 'Cidade/UF', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('97a3e137-c838-56c2-a24a-412c2cbb0de1', '60a2b5cb-f4b3-5aec-9931-c6d2c2e5f917', null, 'data_assinatura', 'Data', 'texto_livre', 2, false, true, null, null, false, null, false);
