-- ============================================================================
-- Seed: Erro Médico / Responsabilidade Médica e Prestação de Serviços
-- ============================================================================
-- Gerado a partir de "Modelo_Final_Laudo_Erro_Medico_Prestacao_Medico_Hospitalar.pdf" (Laudos e
-- documentos/). 27 seções (I-XXV, XXVII, XXVIII) — a numeração do modelo original tem 28 itens +
-- 1 anexo, mas duas partes NÃO viram seções preenchíveis (ver notas abaixo).
--
-- Achados ao mapear este modelo (ver resumo enviado à Dra. Fernanda p/ conferência):
--  - O modelo original tem DUAS seções endereçadas explicitamente "para o sistema"/"para o
--    programador" (XXVI "Alertas e Travas para o Sistema" e o ANEXO final "Regras de Implementação
--    para o Programador") — são instruções de validação/lógica, não conteúdo de laudo, e por isso NÃO
--    viraram secoes. O conteúdo delas foi incorporado como decisões de modelagem abaixo (condicao de
--    seções, requer_confirmacao_perito nas conclusões sensíveis, tabelas dinâmicas p/ múltiplos
--    agentes/condutas, etc.).
--  - Diferente de Curatela/Previdenciário/Trabalhista, este modelo NÃO usa o padrão "exame físico por
--    sistema fechado com 4 opções + parent_campo_id": a Seção XII apresenta os sistemas como UMA
--    tabela (3 estados — Normal/Alterado/Não avaliado — sem "Avaliação prejudicada" — + Achados
--    objetivos + Repercussão funcional sempre visíveis). Reproduzido fielmente como tipo_campo =
--    'tabela' (linhas fixas x múltiplas colunas), não como parent_campo_id/condicao.
--  - Seção XII usa o novo mecanismo de condicao combinada ("todas": [...] — E lógico entre
--    condições simples, ver src/types/json-fields.ts e src/features/preenchimento/condicoes.ts):
--    só aparece com periciando(a) vivo(a) E perícia não-indireta. Curatela/Previdenciário/Trabalhista
--    continuam usando só a forma simples (um campo, uma lista de valores_gatilho) — 100% compatível,
--    nenhuma migration precisou mudar.
--  - Seção XXVII "Quadro-Resumo para o Juízo" recapitula respostas de outras seções (Modalidade,
--    Situação do periciando, Documentação, TCLE, Contrato, as 3 camadas da conclusão, etc.). Não há
--    campo novo — modelada como seção estrutural com texto_automatico_template (mesmo mecanismo já
--    usado pra 'Matriz de Documentos Analisados' nos outros 3 tipos), recompondo os {{codigo_campo}}
--    já respondidos alhures. NÃO reproduz o layout de tabela do PDF — vira parágrafo de recapitulação.
--  - Seção XVI ("Análise das Condutas Médicas Questionadas"): o PDF apresenta a matriz por conduta
--    em layout vertical (Campo | Preenchimento, uma linha por atributo) com instrução "cadastrar uma
--    matriz para cada conduta" — ou seja, múltiplos registros repetidos. Reproduzido com o mecanismo
--    genérico de tabela de linhas dinâmicas (mesmo do Previdenciário/Trabalhista), só que virado 90°:
--    cada LINHA da nossa tabela = uma conduta questionada, cada COLUNA = um dos atributos que no PDF
--    apareciam como linha da matriz vertical. Mesmo dado, orientação diferente.
--  - Seção XXIII (Discussão Médico-Legal): o parágrafo automático do PDF referencia elementos que só
--    existem agregados em tabelas dinâmicas (cronologia, condutas, confronto técnico, matriz de
--    agentes) — não é possível resolver isso com o mecanismo de placeholder {{codigo_campo}} (valor
--    único), que só referencia campos de seleção/texto simples, não linhas de tabela. O
--    texto_automatico_template abaixo foi SIMPLIFICADO para usar só os campos diretamente endereçáveis;
--    o campo 'Discussão individualizada' (texto livre) continua existindo pra perita escrever a síntese
--    real puxando das tabelas manualmente. Ver ponto de julgamento no resumo enviado à Dra. Fernanda.
--  - selecao_unica vs. selecao_multipla: heurística do CLAUDE.md (opção 'Ambos'/coringa explícita OU
--    mutuamente excludente = única; combinável = múltipla). 'Modalidade' (III) tem 'Mista' como a
--    própria opção combinada, então fica única. 'Dano atualmente constatável' (XII) e 'Dano
--    atualmente constatável'-like lists misturam um 'Ausente' logicamente excludente com tipos
--    combináveis — seguido o mesmo precedente dos 3 tipos já populados (fica múltipla). Vale conferir
--    no resumo seção a seção.
--  - Nenhuma migration nova foi necessária: todas as colunas usadas (texto_automatico_template em
--    secoes, config_tabela com linhas_dinamicas, requer_confirmacao_perito) já existem no schema.
-- ============================================================================

insert into public.tipos_laudo (id, codigo, nome, descricao, ordem, ativo) values
  ('0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'erro_medico', 'Erro Médico / Responsabilidade Médica e Prestação de Serviços',
   'Avaliação médico-legal de alegações de inadequação da assistência médica, hospitalar, clínica, cirúrgica, anestésica, multiprofissional ou domiciliar, com separação entre adequação técnico-assistencial, dano e nexo causal/concausal.', 4, true);

insert into public.secoes (id, tipo_laudo_id, codigo, titulo, ordem, condicional, condicao, texto_automatico_template) values
  ('0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'identificacao_perito', 'I — Identificação do(a) Perito(a) Judicial', 1, false, null, null),
  ('b055ed03-bed5-5af5-b91a-495f13c9ab41', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'identificacao_periciando', 'II — Identificação do(a) Periciando(a)', 2, false, null, null),
  ('d25e2e8f-dc20-5a04-8a3b-bed1121e5706', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'caracterizacao_pericia', 'III — Caracterização da Perícia', 3, false, null, null),
  ('382b8630-7ca9-5587-be9a-1460d9b3f962', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'objeto_medico_legal', 'IV — Objeto Médico-Legal', 4, false, null, null),
  ('7288c3fa-bc38-5fc9-a561-e0011c77c2d0', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'metodologia', 'V — Metodologia', 5, false, null, null),
  ('4b9c8803-e5bd-5628-a67e-5a74f9c8dd07', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'matriz_documentos_analisados', 'VI — Matriz dos Documentos Analisados', 6, false, null, 'Foram analisados {{total_documentos}} documentos, totalizando {{total_paginas}} páginas, compreendendo {{categorias_principais}}, com suficiência documental global classificada como {{suficiencia_documental_global}}.'),
  ('8436b56b-0360-5d31-a9bd-9b513f0f17dd', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'auditoria_tcle', 'VII — Auditoria do Termo de Consentimento Livre e Esclarecido — TCLE', 7, false, null, null),
  ('8f00458f-bede-5ca6-89af-a139e5fa8b67', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'contrato_documentacao_prestacao_servicos', 'VIII — Contrato / Documentação da Prestação de Serviços', 8, false, null, null),
  ('bcef3eee-1128-5fcc-80f2-422d09570157', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'reconstrucao_cronologica_assistencia', 'IX — Reconstrução Cronológica da Assistência', 9, false, null, 'Cadastrar cada evento de forma individual. O sistema permite ordenação automática por data/hora e gera narrativa cronológica a partir dos eventos cadastrados.'),
  ('c97f1bbe-d722-5b45-ba8e-fa130db630d8', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'estado_anterior_fatores_risco', 'X — Estado Anterior e Fatores de Risco', 10, false, null, null),
  ('4834349f-a1bf-532a-9f9b-d01680cc9a16', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'historia_clinica_evolucao', 'XI — História Clínica e Evolução', 11, false, null, null),
  ('15252665-17e6-56fb-b1be-3e7973dc5301', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'exame_medico_pericial_direto', 'XII — Exame Médico-Pericial Direto — quando aplicável', 12, true, '{"todas": [{"campo_codigo": "situacao_vital", "valores_gatilho": ["vivo"]}, {"campo_codigo": "modalidade_pericia", "valores_gatilho": ["direta", "mista", "outra_modalidade_admitida"]}]}'::jsonb, null),
  ('8a7a1e95-8330-5c71-9de6-51805d83c0a2', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'modulo_home_care', 'XIII — Módulo Home Care / Assistência Domiciliar', 13, true, '{"campo_codigo": "situacao_assistencial_atual", "valores_gatilho": ["home_care"]}'::jsonb, null),
  ('273bc4c0-7568-5a1b-9ff8-d47bae821c29', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'modulo_obito_pericia_indireta', 'XIV — Módulo de Óbito / Perícia Indireta', 14, true, '{"campo_codigo": "situacao_vital", "valores_gatilho": ["falecido"]}'::jsonb, null),
  ('136b0fc3-3f37-5b9f-9382-8346ae09eb13', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'auditoria_prontuario_qualidade_documental', 'XV — Auditoria do Prontuário e Qualidade Documental', 15, false, null, null),
  ('1bd7b503-ae45-5f56-9875-25dc0c849ee7', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'analise_condutas_medicas_questionadas', 'XVI — Análise das Condutas Médicas Questionadas', 16, false, null, 'Cadastrar uma matriz para cada conduta, profissional ou momento decisório questionado.'),
  ('f539debe-3f54-5041-ab58-3f2dee0fef16', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'analise_prestacao_medico_hospitalar', 'XVII — Análise da Prestação Médico-Hospitalar', 17, false, null, null),
  ('3d99aefc-1290-5d04-b394-7f030fa219b9', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'confronto_padrao_tecnico_literatura', 'XVIII — Confronto com o Padrão Técnico e Literatura', 18, false, null, null),
  ('b10b32d8-c9e5-56de-adc2-47342ae34d58', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'caracterizacao_desfecho_dano', 'XIX — Caracterização do Desfecho / Dano', 19, false, null, null),
  ('26db7016-dd3c-575c-9de8-028a1d3e9eb1', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'nexo_causal_concausalidade', 'XX — Nexo Causal e Concausalidade', 20, false, null, null),
  ('98d679ca-f7c7-5026-95d5-5d6544965105', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'matriz_agente_reu_prestador', 'XXI — Matriz por Agente / Réu / Prestador', 21, false, null, null),
  ('e3f7e1ec-918d-5d2b-a547-df3704947483', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'tres_camadas_conclusao', 'XXII — Três Camadas Obrigatórias da Conclusão', 22, false, null, 'TRAVA CENTRAL: inadequação documental ou técnica não deve gerar automaticamente nexo causal. Da mesma forma, resultado adverso ou complicação não deve gerar automaticamente inadequação assistencial.'),
  ('ba332ded-e910-57e3-aa0f-4a0d85130236', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'discussao_medico_legal', 'XXIII — Discussão Médico-Legal', 23, false, null, 'O(a) periciando(a) apresentava, previamente ao evento assistencial discutido, {{descricao_estado_anterior}}. Do ponto de vista clínico, o quadro correspondeu a {{queixa_diagnostico_inicial}}. No confronto com o padrão técnico aplicável ao contexto, a classificação global foi de {{classificacao_global_confronto}}. O desfecho consistiu em {{classificacao_medico_pericial_desfecho}}, caracterizado objetivamente por {{dano_objetivamente_demonstrado}}, com sequelas atuais de {{sequelas_atuais}}. Consideradas a temporalidade, a plausibilidade fisiopatológica, o estado anterior e as causas alternativas, a relação causal é classificada como {{nexo_causal_resultado}}. As limitações documentais relevantes são {{impacto_fragilidades_documentais_sobre_analise}}.'),
  ('9cf2be03-f9f3-55e6-ad66-0d74b6c6f0fa', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'conclusao_medico_pericial', 'XXIV — Conclusão Médico-Pericial', 24, false, null, null),
  ('4911ddfb-6ae9-5073-9fdb-90c55e444781', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'respostas_quesitos', 'XXV — Respostas aos Quesitos', 25, false, null, null),
  ('49ed6b95-2eb7-5068-a187-c535debe3ab8', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'quadro_resumo_juizo', 'XXVII — Quadro-Resumo para o Juízo', 26, false, null, 'Modalidade da perícia: {{modalidade_pericia}}. Situação do periciando: {{situacao_vital}}. Documentação: {{suficiencia_documental_global}}. TCLE: {{tcle_status}}. Contrato de prestação: {{contrato_apresentado}}. Adequação técnico-assistencial: {{camada_adequacao_tecnico_assistencial}}. Dano: {{camada_existencia_dano}}. Nexo: {{camada_relacao_causal}}. Estado anterior/concausas: {{concausas_causas_alternativas}}. Prognóstico: {{prognostico}}.'),
  ('09522b45-0c2c-54d5-99a6-207bf21591ed', '0d803fa0-a82c-5dd2-aa29-2ca93b343892', 'encerramento', 'XXVIII — Encerramento', 27, false, null, 'O presente laudo expressa o entendimento técnico deste(a) Médico(a) Perito(a) Judicial, fundamentado nos elementos disponibilizados nos autos, no exame pericial quando realizado, na reconstrução documental da assistência e nos referenciais técnico-científicos pertinentes ao objeto da demanda. As conclusões restringem-se à matéria médico-pericial, cabendo ao Juízo a valoração jurídica dos fatos, a definição de culpa, responsabilidade civil, obrigação de indenizar e demais consequências jurídicas. Permanecendo à disposição para eventuais esclarecimentos. {{cidade_uf_assinatura}}, {{data_assinatura}}. Dr(a). {{nome_perito}}, Médico(a) Perito(a) Judicial, CRM/{{crm_uf}}, RQE nº {{rqe}}, se houver. Documento assinado eletronicamente.');

insert into public.campos_secao (id, secao_id, parent_campo_id, codigo, rotulo, tipo_campo, ordem, obrigatorio, aceita_texto_livre, opcoes, config_tabela, condicional, condicao, requer_confirmacao_perito) values
  ('a68be327-5de8-59fa-aeb1-0945ae742be8', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'nome_perito', 'Nome', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('66b0fddf-8ab8-5b77-af5e-cd056eb2957e', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'crm_uf', 'CRM/UF', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('8c11ed8b-1105-5b21-8bec-675d7a3d320c', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'especialidade', 'Especialidade', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('e0b41c50-f30b-52f8-afca-2da5f6a3010b', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'rqe', 'RQE', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('dd4537be-c2c4-53ac-829e-71afa23bb451', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'data_pericia', 'Data da perícia', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('9f381ef5-253d-5660-8fa5-a685a2a40fdb', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'local_pericia', 'Local', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('c837f133-dc03-5aea-9a26-7203d2e23cff', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'horario_inicio', 'Horário de início', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('7ba16abc-bcba-5f69-a1c2-8e354172a862', '0bc1cfcd-3997-50cc-abb0-8089c6cf71c0', null, 'horario_termino', 'Horário de término', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('8428aa3c-896c-5edd-b245-013dca48c364', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'nome_completo', 'Nome completo', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('d35bbf6d-d5bf-5edf-81cc-a0a7262bef03', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'data_nascimento', 'Data de nascimento', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('84325af1-a454-5de7-b742-6211d7a130b3', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'idade', 'Idade', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('b494560b-79b5-5b39-857e-76a2996df35e', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'cpf_documento', 'CPF/documento', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('5876c990-bf58-5750-9670-187ee8bd0204', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'profissao', 'Profissão', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('d58a08f7-f980-5a49-b01c-a52ec7dc9d6e', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'endereco', 'Endereço', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('3c3f31d1-5186-55a4-b9b6-d08c384c89ac', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'situacao_vital', 'Situação vital', 'selecao_unica', 7, false, true, '[{"codigo": "vivo", "rotulo": "Vivo(a)"}, {"codigo": "falecido", "rotulo": "Falecido(a)"}]'::jsonb, null, false, null, false),
  ('3549997b-4a43-5a2b-bb09-3b67ea0150d2', 'b055ed03-bed5-5af5-b91a-495f13c9ab41', null, 'situacao_assistencial_atual', 'Situação assistencial atual', 'selecao_unica', 8, false, true, '[{"codigo": "sem_tratamento_atual", "rotulo": "Sem tratamento atual"}, {"codigo": "tratamento_ambulatorial", "rotulo": "Tratamento ambulatorial"}, {"codigo": "internado", "rotulo": "Internado(a)"}, {"codigo": "reabilitacao", "rotulo": "Reabilitação"}, {"codigo": "home_care", "rotulo": "Home Care/assistência domiciliar"}, {"codigo": "institucionalizado", "rotulo": "Institucionalizado(a)"}, {"codigo": "tratamento_encerrado", "rotulo": "Tratamento encerrado"}, {"codigo": "cuidados_paliativos", "rotulo": "Cuidados paliativos"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('f408082a-15bf-5573-adc3-77606d24535e', 'd25e2e8f-dc20-5a04-8a3b-bed1121e5706', null, 'modalidade_pericia', 'Modalidade', 'selecao_unica', 1, false, true, '[{"codigo": "direta", "rotulo": "Direta — exame pessoal do(a) periciando(a)"}, {"codigo": "indireta", "rotulo": "Indireta — exclusivamente documental"}, {"codigo": "mista", "rotulo": "Mista — exame direto + análise documental"}, {"codigo": "outra_modalidade_admitida", "rotulo": "Outra modalidade admitida pelo Juízo"}]'::jsonb, null, false, null, false),
  ('4dc40de9-b503-5bbe-8a51-3c2774d5c922', 'd25e2e8f-dc20-5a04-8a3b-bed1121e5706', null, 'motivo_pericia_indireta', 'Motivo da perícia indireta, quando aplicável', 'selecao_multipla', 2, false, true, '[{"codigo": "periciando_falecido", "rotulo": "Periciando(a) falecido(a)"}, {"codigo": "impossibilidade_clinica_comparecimento", "rotulo": "Impossibilidade clínica de comparecimento"}, {"codigo": "objeto_exclusivamente_documental", "rotulo": "Objeto exclusivamente documental"}, {"codigo": "determinacao_judicial", "rotulo": "Determinação judicial"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, true, '{"campo_codigo": "modalidade_pericia", "valores_gatilho": ["indireta", "mista"]}'::jsonb, false),
  ('dbea224c-0399-5431-ad8b-bae0ad6bd98c', 'd25e2e8f-dc20-5a04-8a3b-bed1121e5706', null, 'justificativa_motivo_pericia_indireta', 'Justificativa', 'texto_livre', 3, false, true, null, null, true, '{"campo_codigo": "modalidade_pericia", "valores_gatilho": ["indireta", "mista"]}'::jsonb, false),
  ('3a68487c-741f-5052-8da6-5af78fb99d56', 'd25e2e8f-dc20-5a04-8a3b-bed1121e5706', null, 'participantes_ato', 'Participantes do ato', 'selecao_multipla', 4, false, true, '[{"codigo": "periciando", "rotulo": "Periciando(a)"}, {"codigo": "representante_legal", "rotulo": "Representante legal"}, {"codigo": "familiar_acompanhante", "rotulo": "Familiar/acompanhante"}, {"codigo": "assistente_tecnico_autora", "rotulo": "Assistente técnico da parte autora"}, {"codigo": "assistente_tecnico_re", "rotulo": "Assistente técnico da parte ré"}, {"codigo": "advogado", "rotulo": "Advogado(a), quando admitido"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('8fae8b89-fc5f-55bc-b416-86b45f1dff4b', 'd25e2e8f-dc20-5a04-8a3b-bed1121e5706', null, 'identificacao_presentes', 'Identificação dos presentes', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('0be1c85a-dcef-5cc3-8b5b-edf180f1e047', '382b8630-7ca9-5587-be9a-1460d9b3f962', null, 'objeto_pericia_importado', 'Objeto fixado pelo Juízo/despacho saneador', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('48f2268a-7477-5a93-9b23-abe8681a17b7', '382b8630-7ca9-5587-be9a-1460d9b3f962', null, 'pontos_controvertidos', 'Pontos controvertidos', 'selecao_multipla', 2, false, true, '[{"codigo": "diagnostico", "rotulo": "Diagnóstico"}, {"codigo": "atraso_diagnostico", "rotulo": "Atraso diagnóstico"}, {"codigo": "erro_discordancia_diagnostica", "rotulo": "Erro/discordância diagnóstica"}, {"codigo": "indicacao_terapeutica", "rotulo": "Indicação terapêutica"}, {"codigo": "tratamento_clinico", "rotulo": "Tratamento clínico"}, {"codigo": "tratamento_cirurgico", "rotulo": "Tratamento cirúrgico"}, {"codigo": "tecnica_operatoria", "rotulo": "Técnica operatória"}, {"codigo": "anestesia", "rotulo": "Anestesia"}, {"codigo": "prescricao_medicamentosa", "rotulo": "Prescrição medicamentosa"}, {"codigo": "monitorizacao", "rotulo": "Monitorização"}, {"codigo": "seguimento_pos_operatorio", "rotulo": "Seguimento pós-operatório"}, {"codigo": "alta_hospitalar", "rotulo": "Alta hospitalar"}, {"codigo": "transferencia_regulacao", "rotulo": "Transferência/regulação"}, {"codigo": "infeccao_relacionada_assistencia", "rotulo": "Infecção relacionada à assistência"}, {"codigo": "queda_evento_adverso", "rotulo": "Queda/evento adverso"}, {"codigo": "falha_vigilancia", "rotulo": "Falha de vigilância"}, {"codigo": "falha_comunicacao", "rotulo": "Falha de comunicação"}, {"codigo": "falha_documental", "rotulo": "Falha documental"}, {"codigo": "consentimento_informado", "rotulo": "Consentimento informado"}, {"codigo": "estrutura_hospitalar", "rotulo": "Estrutura hospitalar"}, {"codigo": "equipe_multiprofissional", "rotulo": "Equipe multiprofissional"}, {"codigo": "home_care", "rotulo": "Home Care"}, {"codigo": "obito", "rotulo": "Óbito"}, {"codigo": "oportunidade_terapeutica_potencialmente_perdida", "rotulo": "Oportunidade terapêutica potencialmente perdida"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('c7580bf7-0d6f-546e-b9e3-df4741c3c424', '382b8630-7ca9-5587-be9a-1460d9b3f962', null, 'questao_medico_pericial_central', 'Questão médico-pericial central', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('90b2e536-ce33-5b75-8f65-61b8579e5c6d', '7288c3fa-bc38-5fc9-a561-e0011c77c2d0', null, 'metodos_empregados', 'Métodos empregados', 'selecao_multipla', 1, false, true, '[{"codigo": "leitura_autos_documentos", "rotulo": "Leitura dos autos/documentos disponibilizados"}, {"codigo": "analise_prontuario", "rotulo": "Análise de prontuário"}, {"codigo": "entrevista_anamnese_pericial", "rotulo": "Entrevista/anamnese pericial"}, {"codigo": "exame_fisico_geral", "rotulo": "Exame físico geral"}, {"codigo": "exame_segmentar", "rotulo": "Exame segmentar"}, {"codigo": "exame_neurologico", "rotulo": "Exame neurológico"}, {"codigo": "exame_psiquico", "rotulo": "Exame psíquico"}, {"codigo": "avaliacao_funcional", "rotulo": "Avaliação funcional"}, {"codigo": "analise_exames_complementares", "rotulo": "Análise de exames complementares"}, {"codigo": "analise_imagens_fotografias_clinicas", "rotulo": "Análise de imagens/fotografias clínicas"}, {"codigo": "analise_tcle", "rotulo": "Análise de TCLE"}, {"codigo": "analise_contrato_prestacao_servicos", "rotulo": "Análise de contrato de prestação de serviços"}, {"codigo": "analise_protocolos_institucionais", "rotulo": "Análise de protocolos institucionais disponíveis"}, {"codigo": "confronto_literatura_diretrizes", "rotulo": "Confronto com literatura/diretrizes científicas pertinentes"}, {"codigo": "reconstrucao_cronologica_assistencia", "rotulo": "Reconstrução cronológica da assistência"}, {"codigo": "analise_causal_medico_legal", "rotulo": "Análise causal médico-legal"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('01402674-6f16-5c59-823e-50004a44a19a', '7288c3fa-bc38-5fc9-a561-e0011c77c2d0', null, 'limitacoes_metodologicas', 'Limitações metodológicas', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('6f9667ec-838e-5162-8348-aa86c9bd0925', '4b9c8803-e5bd-5628-a67e-5a74f9c8dd07', null, 'suficiencia_documental_global', 'Suficiência documental global', 'selecao_unica', 1, false, true, '[{"codigo": "suficiente", "rotulo": "Suficiente"}, {"codigo": "parcialmente_suficiente", "rotulo": "Parcialmente suficiente"}, {"codigo": "insuficiente", "rotulo": "Insuficiente"}, {"codigo": "necessita_complementacao", "rotulo": "Necessita complementação"}]'::jsonb, null, false, null, false),
  ('0efa85e2-57c4-53fc-a1b6-8ba470a44421', '4b9c8803-e5bd-5628-a67e-5a74f9c8dd07', null, 'documentos_ausentes_relevantes', 'Documentos ausentes relevantes', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('c7a6f089-ec1e-57ff-92ff-1b4b2754be7d', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_status', 'TCLE', 'selecao_unica', 1, false, true, '[{"codigo": "apresentado", "rotulo": "Apresentado"}, {"codigo": "nao_apresentado", "rotulo": "Não apresentado"}, {"codigo": "nao_aplicavel", "rotulo": "Não aplicável ao ato discutido"}]'::jsonb, null, false, null, false),
  ('d8d9a6bd-ea62-576a-bcb0-1a14ef310025', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_caracteristicas', 'Características', 'selecao_multipla', 2, false, true, '[{"codigo": "individualizado", "rotulo": "Individualizado"}, {"codigo": "generico_padronizado", "rotulo": "Genérico/padronizado"}, {"codigo": "completo", "rotulo": "Completo"}, {"codigo": "incompleto", "rotulo": "Incompleto"}, {"codigo": "legivel", "rotulo": "Legível"}, {"codigo": "ilegivel_parcialmente_legivel", "rotulo": "Ilegível/parcialmente legível"}, {"codigo": "datado", "rotulo": "Datado"}, {"codigo": "sem_data", "rotulo": "Sem data"}, {"codigo": "assinado_paciente", "rotulo": "Assinado pelo(a) paciente"}, {"codigo": "assinado_representante_legal", "rotulo": "Assinado por representante legal"}, {"codigo": "assinado_medico_responsavel", "rotulo": "Assinado pelo médico/profissional responsável"}, {"codigo": "sem_identificacao_profissional_esclarecimentos", "rotulo": "Sem identificação do profissional que prestou esclarecimentos"}]'::jsonb, null, false, null, false),
  ('7a2a73fc-907b-5e2b-8313-bcdedb3e074f', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_temporalidade', 'Temporalidade', 'selecao_unica', 3, false, true, '[{"codigo": "anterior_procedimento", "rotulo": "Anterior ao procedimento"}, {"codigo": "mesmo_dia_antes_procedimento", "rotulo": "No mesmo dia, antes do procedimento"}, {"codigo": "mesmo_dia_sem_horario_verificavel", "rotulo": "No mesmo dia sem horário verificável"}, {"codigo": "posterior_procedimento", "rotulo": "Posterior ao procedimento"}, {"codigo": "indeterminada", "rotulo": "Indeterminada"}]'::jsonb, null, false, null, false),
  ('debdb02a-7b1e-533f-b415-f8ff4a170df1', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_conteudo_identificavel', 'Conteúdo identificável', 'selecao_multipla', 4, false, true, '[{"codigo": "diagnostico_indicacao", "rotulo": "Diagnóstico/indicação"}, {"codigo": "natureza_procedimento", "rotulo": "Natureza do procedimento"}, {"codigo": "beneficios_esperados", "rotulo": "Benefícios esperados"}, {"codigo": "riscos_gerais", "rotulo": "Riscos gerais"}, {"codigo": "riscos_especificos_relevantes", "rotulo": "Riscos específicos relevantes"}, {"codigo": "alternativas_terapeuticas", "rotulo": "Alternativas terapêuticas"}, {"codigo": "possibilidade_nao_tratamento", "rotulo": "Possibilidade de não tratamento"}, {"codigo": "consequencias_previsiveis", "rotulo": "Consequências previsíveis"}, {"codigo": "possibilidade_conversao_alteracao_tecnica", "rotulo": "Possibilidade de conversão/alteração técnica"}, {"codigo": "materiais_proteses_quando_pertinentes", "rotulo": "Materiais/próteses quando pertinentes"}, {"codigo": "cuidados_pos_procedimento", "rotulo": "Cuidados pós-procedimento"}, {"codigo": "espaco_duvidas", "rotulo": "Espaço para dúvidas"}, {"codigo": "nenhum_insuficiente", "rotulo": "Nenhum/insuficiente"}]'::jsonb, null, false, null, false),
  ('6b52471b-e572-5b7e-b542-f1b50902a68a', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_avaliacao_documental_consentimento', 'Avaliação médico-documental do processo de consentimento', 'selecao_unica', 5, false, true, '[{"codigo": "adequadamente_documentado", "rotulo": "Adequadamente documentado"}, {"codigo": "parcialmente_documentado", "rotulo": "Parcialmente documentado"}, {"codigo": "documentacao_insuficiente", "rotulo": "Documentação insuficiente"}, {"codigo": "nao_documentado", "rotulo": "Não documentado"}]'::jsonb, null, false, null, false),
  ('d3907fc3-b194-5279-9f00-b1fbd452effd', '8436b56b-0360-5d31-a9bd-9b513f0f17dd', null, 'tcle_analise_critica', 'Análise crítica do TCLE', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('c3e6b88f-2d14-5397-a40b-b263fbb22c5f', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'contrato_apresentado', 'Contrato apresentado?', 'selecao_unica', 1, false, true, '[{"codigo": "sim", "rotulo": "Sim"}, {"codigo": "nao", "rotulo": "Não"}, {"codigo": "parcialmente", "rotulo": "Parcialmente"}, {"codigo": "nao_aplicavel", "rotulo": "Não aplicável"}]'::jsonb, null, false, null, false),
  ('8ee73589-7207-5be3-af47-4fdfa6498dde', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'relacao_documentada', 'Relação documentada', 'selecao_multipla', 2, false, true, '[{"codigo": "medico_paciente", "rotulo": "Médico-paciente"}, {"codigo": "clinica_paciente", "rotulo": "Clínica-paciente"}, {"codigo": "hospital_paciente", "rotulo": "Hospital-paciente"}, {"codigo": "operadora_plano_paciente", "rotulo": "Operadora/plano-paciente"}, {"codigo": "home_care_paciente", "rotulo": "Home Care-paciente"}, {"codigo": "prestador_terceirizado", "rotulo": "Prestador terceirizado"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('fc686637-7369-57a2-b44c-a2b23c1b65f4', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'objeto_procedimento_contratado', 'Objeto/procedimento contratado', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('e4f82366-4988-54cb-b418-f5669482cf39', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'profissionais_servicos_previstos', 'Profissionais/serviços previstos', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('900a2fb6-7519-5d62-83d4-526bed6a45cb', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'materiais_proteses_opme_previstos', 'Materiais/próteses/OPME previstos', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('859fb37e-cdc6-538a-8db2-dd0aa6228472', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'acompanhamento_retornos_previstos', 'Acompanhamento/retornos previstos', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('7179b5ee-6eda-5617-b0fc-7b177cb16fce', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'obrigacoes_assistenciais_relevantes_documentadas', 'Obrigações assistenciais relevantes documentadas', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('eff12b4d-b948-502a-942a-005fddf59f13', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'correspondencia_servico_assistencia', 'Correspondência entre serviço documentado e assistência realizada', 'selecao_unica', 8, false, true, '[{"codigo": "correspondente", "rotulo": "Correspondente"}, {"codigo": "parcialmente_correspondente", "rotulo": "Parcialmente correspondente"}, {"codigo": "divergente", "rotulo": "Divergente"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, false),
  ('6997e059-6505-5136-9eba-3fbdfe330ac8', '8f00458f-bede-5ca6-89af-a139e5fa8b67', null, 'divergencias_relevantes_contrato', 'Divergências relevantes', 'texto_livre', 9, false, true, null, null, false, null, false),
  ('97c69fe3-a5e2-5ad2-97fd-e94fae9456b6', 'bcef3eee-1128-5fcc-80f2-422d09570157', null, 'cronologia_assistencia', 'Cronologia da assistência', 'tabela', 1, false, true, null, '{"linhas": [], "linhas_dinamicas": true, "colunas": [{"codigo": "data_hora", "rotulo": "Data/hora", "tipo": "texto_livre"}, {"codigo": "estado_clinico", "rotulo": "Estado clínico", "tipo": "texto_livre"}, {"codigo": "profissional_equipe", "rotulo": "Profissional/Equipe", "tipo": "texto_livre"}, {"codigo": "avaliacao_hipotese", "rotulo": "Avaliação/hipótese", "tipo": "texto_livre"}, {"codigo": "conduta", "rotulo": "Conduta", "tipo": "texto_livre"}, {"codigo": "exames_resultado", "rotulo": "Exames/resultado", "tipo": "texto_livre"}, {"codigo": "evolucao", "rotulo": "Evolução", "tipo": "texto_livre"}, {"codigo": "analise_tecnica", "rotulo": "Análise técnica", "tipo": "texto_livre"}]}'::jsonb, false, null, false),
  ('aa51533f-6848-5b79-bcd4-1b2d1a72fa7e', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'condicoes_clinicas_previas', 'Condições clínicas prévias', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('cd8b784c-6976-5107-bf81-1a566a583059', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'comorbidades', 'Comorbidades', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('5ba7c61a-2a91-5a77-950c-437f5b029a91', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'cirurgias_procedimentos_anteriores', 'Cirurgias/procedimentos anteriores', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('5e264aec-cfec-5a27-a10f-cd6b0b4bd6d0', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'medicamentos_previos', 'Medicamentos prévios', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('73b16828-88c3-50f8-ba77-e3f0e5fe2c2a', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'alergias', 'Alergias', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('53a1e998-3d7d-560a-b027-854703904163', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'fatores_risco_relevantes', 'Fatores de risco relevantes', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('10a581be-a70f-5697-9c3d-4c7edd23a983', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'estado_funcional_anterior', 'Estado funcional anterior', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('7433b969-28b3-5bc3-8898-8999ab49265d', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'dano_ja_existia_antes_assistencia', 'O dano/limitação alegado já existia antes da assistência questionada?', 'selecao_unica', 8, false, true, '[{"codigo": "nao", "rotulo": "Não"}, {"codigo": "sim_integralmente", "rotulo": "Sim, integralmente"}, {"codigo": "sim_parcialmente", "rotulo": "Sim, parcialmente"}, {"codigo": "nao_possivel_determinar", "rotulo": "Não é possível determinar"}]'::jsonb, null, false, null, false),
  ('48314d16-ba12-5fd2-91ab-7c6273e3eef7', 'c97f1bbe-d722-5b45-ba8e-fa130db630d8', null, 'descricao_estado_anterior', 'Descrição do estado anterior', 'texto_livre', 9, false, true, null, null, false, null, false),
  ('f18d588c-bf87-5394-88d0-322b4e432ac5', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'queixa_diagnostico_inicial', 'Queixa/diagnóstico inicial', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('b43ef66e-c23b-5b73-8722-80dc4e12836c', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'sinais_sintomas_apresentacao', 'Sinais e sintomas de apresentação', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('f75def82-66fc-5c30-bd3b-72e5760fc0d1', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'hipoteses_diagnosticas_registradas', 'Hipóteses diagnósticas registradas', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('2248fe42-065e-5ec8-99a0-9bdce9703658', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'tratamentos_realizados', 'Tratamentos realizados', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('c8a106de-ae5f-5fb7-8d57-c0b0ffdafb60', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'procedimentos_cirurgias', 'Procedimentos/cirurgias', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('5f3b61b5-a1be-5024-904d-121f7ba09c05', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'complicacoes_intercorrencias', 'Complicações/intercorrências', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('8e14c426-365e-54aa-9ff4-17a954ca678d', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'reinternacoes_reoperacoes', 'Reinternações/reoperações', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('4542aa7b-3464-5f96-9e9c-33ea7f40b509', '4834349f-a1bf-532a-9f9b-d01680cc9a16', null, 'evolucao_estado_atual_obito', 'Evolução até o estado atual/óbito', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('74b99875-da66-52aa-93b3-d8babbb00695', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'estado_geral', 'Estado geral', 'selecao_unica', 1, false, true, '[{"codigo": "bom", "rotulo": "Bom"}, {"codigo": "regular", "rotulo": "Regular"}, {"codigo": "comprometido", "rotulo": "Comprometido"}, {"codigo": "grave", "rotulo": "Grave"}]'::jsonb, null, false, null, false),
  ('a4485545-084c-515b-985e-d19cceab760f', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'consciencia_orientacao', 'Consciência/orientação', 'selecao_unica', 2, false, true, '[{"codigo": "preservadas", "rotulo": "Preservadas"}, {"codigo": "alteradas", "rotulo": "Alteradas"}, {"codigo": "nao_avaliaveis", "rotulo": "Não avaliáveis"}]'::jsonb, null, false, null, false),
  ('d3f3ce48-7908-5771-b5a2-2932d62fd97e', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'sinais_vitais_pertinentes', 'Sinais vitais, quando pertinentes', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('e305cfdc-79cb-564f-bf14-687db09b83b6', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'exame_por_sistemas', 'Exame por sistema/segmento', 'tabela', 4, false, true, null, '{"linhas": [{"codigo": "cabeca_pescoco_sentidos", "rotulo": "Cabeça/pescoço/sentidos"}, {"codigo": "cardiovascular", "rotulo": "Cardiovascular"}, {"codigo": "respiratorio", "rotulo": "Respiratório"}, {"codigo": "abdominal_digestorio", "rotulo": "Abdominal/digestório"}, {"codigo": "geniturinario", "rotulo": "Geniturinário"}, {"codigo": "musculoesqueletico", "rotulo": "Musculoesquelético"}, {"codigo": "neurologico", "rotulo": "Neurológico"}, {"codigo": "psiquiatrico_cognitivo", "rotulo": "Psiquiátrico/cognitivo"}, {"codigo": "dermatologico_cicatrizes", "rotulo": "Dermatológico/cicatrizes"}, {"codigo": "outro", "rotulo": "Outro"}], "colunas": [{"codigo": "estado", "rotulo": "Estado", "tipo": "selecao_unica", "opcoes": [{"codigo": "normal", "rotulo": "Normal"}, {"codigo": "alterado", "rotulo": "Alterado"}, {"codigo": "nao_avaliado", "rotulo": "Não avaliado"}]}, {"codigo": "achados_objetivos", "rotulo": "Achados objetivos", "tipo": "texto_livre"}, {"codigo": "repercussao_funcional", "rotulo": "Repercussão funcional", "tipo": "texto_livre"}]}'::jsonb, false, null, false),
  ('71cf634b-e9dc-5b4a-aeac-5b75c22d895e', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'dano_atualmente_constatavel', 'Dano atualmente constatável', 'selecao_multipla', 5, false, true, '[{"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "temporario", "rotulo": "Temporário"}, {"codigo": "permanente", "rotulo": "Permanente"}, {"codigo": "anatomico", "rotulo": "Anatômico"}, {"codigo": "funcional", "rotulo": "Funcional"}, {"codigo": "neurologico", "rotulo": "Neurológico"}, {"codigo": "cognitivo", "rotulo": "Cognitivo"}, {"codigo": "psiquico", "rotulo": "Psíquico"}, {"codigo": "estetico", "rotulo": "Estético"}, {"codigo": "sensorial", "rotulo": "Sensorial"}, {"codigo": "reprodutivo", "rotulo": "Reprodutivo"}, {"codigo": "dor_cronica", "rotulo": "Dor crônica"}, {"codigo": "dependencia_terceiros", "rotulo": "Dependência de terceiros"}, {"codigo": "necessidade_dispositivo", "rotulo": "Necessidade de dispositivo"}, {"codigo": "necessidade_tratamento_continuado", "rotulo": "Necessidade de tratamento continuado"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('fe70994b-a3c3-59f9-aec2-f90426eab75f', '15252665-17e6-56fb-b1be-3e7973dc5301', null, 'descricao_detalhada_dano', 'Descrição detalhada', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('2b9af161-f12e-5827-85e3-3fd0d8e05c7c', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'indicacao_clinica_home_care', 'Indicação clínica do Home Care', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('39dbcbe3-1e44-5fec-9676-e9c9f1a1042e', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'nivel_dependencia', 'Nível de dependência', 'selecao_unica', 2, false, true, '[{"codigo": "independente", "rotulo": "Independente"}, {"codigo": "dependencia_leve", "rotulo": "Dependência leve"}, {"codigo": "moderada", "rotulo": "Moderada"}, {"codigo": "importante", "rotulo": "Importante"}, {"codigo": "total", "rotulo": "Total"}]'::jsonb, null, false, null, false),
  ('57b5e928-3fe5-587c-9fc9-b1254c26f4d7', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'dispositivos_suportes', 'Dispositivos/suportes', 'selecao_multipla', 3, false, true, '[{"codigo": "oxigenoterapia", "rotulo": "Oxigenoterapia"}, {"codigo": "ventilacao_nao_invasiva", "rotulo": "Ventilação não invasiva"}, {"codigo": "ventilacao_invasiva", "rotulo": "Ventilação invasiva"}, {"codigo": "traqueostomia", "rotulo": "Traqueostomia"}, {"codigo": "gastrostomia", "rotulo": "Gastrostomia"}, {"codigo": "sonda_enteral", "rotulo": "Sonda enteral"}, {"codigo": "sonda_vesical", "rotulo": "Sonda vesical"}, {"codigo": "cateter_venoso", "rotulo": "Cateter venoso"}, {"codigo": "ostomia", "rotulo": "Ostomia"}, {"codigo": "aspiracao_frequente", "rotulo": "Aspiração frequente"}, {"codigo": "outro", "rotulo": "Outro"}, {"codigo": "nenhum", "rotulo": "Nenhum"}]'::jsonb, null, false, null, false),
  ('9afa398f-d5c2-5735-b565-6f0ed3f55cc6', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'assistencia_requerida', 'Assistência requerida', 'selecao_multipla', 4, false, true, '[{"codigo": "medico", "rotulo": "Médico"}, {"codigo": "enfermagem_24h", "rotulo": "Enfermagem 24h"}, {"codigo": "enfermagem_parcial", "rotulo": "Enfermagem parcial"}, {"codigo": "tecnico_enfermagem", "rotulo": "Técnico de enfermagem"}, {"codigo": "fisioterapia_motora", "rotulo": "Fisioterapia motora"}, {"codigo": "fisioterapia_respiratoria", "rotulo": "Fisioterapia respiratória"}, {"codigo": "fonoaudiologia", "rotulo": "Fonoaudiologia"}, {"codigo": "nutricao", "rotulo": "Nutrição"}, {"codigo": "terapia_ocupacional", "rotulo": "Terapia ocupacional"}, {"codigo": "psicologia", "rotulo": "Psicologia"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('5a73b92c-8a8b-572c-874f-5e6ae2cd7929', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'frequencia_atualmente_prescrita', 'Frequência atualmente prescrita', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('8230f3c3-6f2d-5593-a65b-8e114a6225d0', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'necessidades_efetivamente_constatadas', 'Necessidades efetivamente constatadas', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('016ad94f-2dd8-5e94-894a-21750e12f87c', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'home_care_atual_avaliacao', 'Home Care atual', 'selecao_unica', 7, false, true, '[{"codigo": "clinicamente_justificado", "rotulo": "Clinicamente justificado"}, {"codigo": "justificado_possibilidade_reducao_progressiva", "rotulo": "Justificado com possibilidade de redução progressiva"}, {"codigo": "necessita_reavaliacao", "rotulo": "Necessita reavaliação"}, {"codigo": "elementos_insuficientes", "rotulo": "Elementos insuficientes"}, {"codigo": "nao_justificado_pelos_elementos_atuais", "rotulo": "Não justificado pelos elementos atuais"}]'::jsonb, null, false, null, false),
  ('603e6fad-ce34-5bd7-b468-4cd78ceab75d', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'possibilidade_desospitalizacao_reducao_suporte', 'Possibilidade de desospitalização/redução de suporte', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('f974cc5c-bba5-5d95-86f7-97b427e86140', '8a7a1e95-8330-5c71-9de6-51805d83c0a2', null, 'riscos_retirada_reducao', 'Riscos de retirada/redução', 'texto_livre', 9, false, true, null, null, false, null, false),
  ('5dcd2090-4056-5203-9a43-d081148a979a', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'data_hora_obito', 'Data/hora do óbito', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('332b6df9-3db6-526c-9782-29e6691231c8', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'local_obito', 'Local', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('3876c013-f9d2-5b27-a82c-9de4bce905f6', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'causa_imediata', 'Causa imediata', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('ad50f233-0f91-55f2-af22-5ec00f846fe1', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'causas_intermediarias', 'Causa(s) intermediária(s)', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('3c93c58f-200c-5d50-90b5-c4de5e2a5a82', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'causa_basica', 'Causa básica', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('5a59096d-51bd-54aa-819f-e613a62991ff', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'fontes_obito', 'Fontes', 'selecao_multipla', 6, false, true, '[{"codigo": "declaracao_obito", "rotulo": "Declaração de óbito"}, {"codigo": "prontuario_terminal", "rotulo": "Prontuário terminal"}, {"codigo": "necropsia_iml", "rotulo": "Necropsia/IML"}, {"codigo": "exames_laboratoriais", "rotulo": "Exames laboratoriais"}, {"codigo": "imagem", "rotulo": "Imagem"}, {"codigo": "relatorios_assistenciais", "rotulo": "Relatórios assistenciais"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('46dc7278-7ce4-5686-8615-d72d7ceb94fd', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'condicao_clinica_admissao_inicio_evento', 'Condição clínica na admissão/início do evento', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('30ea2a2e-d1bf-539a-a64c-2bca84c0869b', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'evolucao_terminal', 'Evolução terminal', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('78e64759-c937-52c9-9fde-d46b47f35f09', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'intervencoes_criticas_realizadas', 'Intervenções críticas realizadas', 'texto_livre', 9, false, true, null, null, false, null, false),
  ('0eff2c2d-50f6-5be2-91b8-2fb0a2fb59a4', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'cadeia_causal_medico_legal', 'Cadeia causal médico-legal', 'selecao_unica', 10, false, true, '[{"codigo": "compativel_evolucao_natural_doenca", "rotulo": "Compatível com evolução natural da doença"}, {"codigo": "compativel_complicacao_reconhecida", "rotulo": "Compatível com complicação reconhecida"}, {"codigo": "possivel_relacao_evento_adverso_assistencial", "rotulo": "Possível relação com evento adverso assistencial"}, {"codigo": "relacao_causal_concausal_demonstrada_inadequacao_assistencial", "rotulo": "Relação causal/concausal demonstrada com inadequação assistencial"}, {"codigo": "indeterminada", "rotulo": "Indeterminada"}]'::jsonb, null, false, null, true),
  ('991e437b-ed7c-5f61-ba98-9de0d3ef9f9a', '273bc4c0-7568-5a1b-9ff8-d47bae821c29', null, 'fundamentacao_cadeia_causal', 'Fundamentação da cadeia causal', 'texto_livre', 11, false, true, null, null, false, null, false),
  ('fc54a53e-ab1d-578b-bda9-9941f7ec61f9', '136b0fc3-3f37-5b9f-9382-8346ae09eb13', null, 'auditoria_prontuario', 'Auditoria do prontuário', 'tabela', 1, false, true, null, '{"linhas": [{"codigo": "identificacao_paciente", "rotulo": "Identificação do paciente"}, {"codigo": "identificacao_profissional", "rotulo": "Identificação profissional"}, {"codigo": "datas_horarios", "rotulo": "Datas e horários"}, {"codigo": "anamnese", "rotulo": "Anamnese"}, {"codigo": "exame_fisico", "rotulo": "Exame físico"}, {"codigo": "hipoteses_diagnosticas", "rotulo": "Hipóteses diagnósticas"}, {"codigo": "plano_conduta", "rotulo": "Plano/conduta"}, {"codigo": "prescricoes_checagens", "rotulo": "Prescrições/checagens"}, {"codigo": "evolucoes_medicas", "rotulo": "Evoluções médicas"}, {"codigo": "enfermagem", "rotulo": "Enfermagem"}, {"codigo": "registros_multiprofissionais", "rotulo": "Registros multiprofissionais"}, {"codigo": "intercorrencias", "rotulo": "Intercorrências"}, {"codigo": "descricao_cirurgica", "rotulo": "Descrição cirúrgica"}, {"codigo": "anestesia", "rotulo": "Anestesia"}, {"codigo": "srpa", "rotulo": "SRPA"}, {"codigo": "exames_complementares", "rotulo": "Exames complementares"}, {"codigo": "alta_transferencia", "rotulo": "Alta/transferência"}, {"codigo": "orientacoes_seguimento", "rotulo": "Orientações/seguimento"}], "colunas": [{"codigo": "estado", "rotulo": "Estado", "tipo": "selecao_unica", "opcoes": [{"codigo": "adequado", "rotulo": "Adequado"}, {"codigo": "parcial", "rotulo": "Parcial"}, {"codigo": "ausente_inadequado", "rotulo": "Ausente/Inadequado"}]}, {"codigo": "observacao", "rotulo": "Observação", "tipo": "texto_livre"}]}'::jsonb, false, null, false),
  ('1c564e00-a937-57a6-aec5-e9f7d8238478', '136b0fc3-3f37-5b9f-9382-8346ae09eb13', null, 'classificacao_situacao_documental', 'Classificação da situação documental', 'selecao_unica', 2, false, true, '[{"codigo": "conduta_documentada_tecnicamente_adequada", "rotulo": "Conduta documentada e tecnicamente adequada"}, {"codigo": "conduta_documentada_possivel_inadequacao_tecnica", "rotulo": "Conduta documentada com possível inadequação técnica"}, {"codigo": "conduta_nao_suficientemente_documentada", "rotulo": "Conduta não suficientemente documentada — impossibilidade de comprovar sua realização"}, {"codigo": "prontuario_globalmente_insuficiente", "rotulo": "Prontuário globalmente insuficiente para reconstrução segura"}, {"codigo": "documentacao_adequada_lacunas_pontuais", "rotulo": "Documentação adequada com lacunas pontuais"}]'::jsonb, null, false, null, false),
  ('71722bd8-840d-5cf7-8582-27da910aa303', '136b0fc3-3f37-5b9f-9382-8346ae09eb13', null, 'impacto_fragilidades_documentais_sobre_analise', 'Impacto das fragilidades documentais sobre a análise', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('c6b952d2-6806-5c34-b346-2fdc79eaa5f1', '1bd7b503-ae45-5f56-9875-25dc0c849ee7', null, 'matriz_condutas_questionadas', 'Matriz por conduta questionada', 'tabela', 1, false, true, null, '{"linhas": [], "linhas_dinamicas": true, "colunas": [{"codigo": "conduta_numero", "rotulo": "Conduta nº", "tipo": "texto_livre"}, {"codigo": "profissional_especialidade", "rotulo": "Profissional/especialidade", "tipo": "texto_livre"}, {"codigo": "data_hora", "rotulo": "Data/hora", "tipo": "texto_livre"}, {"codigo": "condicao_clinica_naquele_momento", "rotulo": "Condição clínica naquele momento", "tipo": "texto_livre"}, {"codigo": "informacoes_disponiveis_profissional", "rotulo": "Informações disponíveis ao profissional", "tipo": "texto_livre"}, {"codigo": "conduta_tecnicamente_esperada", "rotulo": "Conduta tecnicamente esperada", "tipo": "texto_livre"}, {"codigo": "conduta_efetivamente_documentada", "rotulo": "Conduta efetivamente documentada", "tipo": "texto_livre"}, {"codigo": "exames_monitorizacao_esperados", "rotulo": "Exames/monitorização esperados", "tipo": "texto_livre"}, {"codigo": "exames_monitorizacao_realizados", "rotulo": "Exames/monitorização realizados", "tipo": "texto_livre"}, {"codigo": "oportunidade_temporal_intervencao", "rotulo": "Oportunidade temporal da intervenção", "tipo": "texto_livre"}, {"codigo": "recursos_disponiveis_conhecidos", "rotulo": "Recursos disponíveis/conhecidos", "tipo": "texto_livre"}, {"codigo": "desfecho_relacionado", "rotulo": "Desfecho relacionado", "tipo": "texto_livre"}]}'::jsonb, false, null, false),
  ('7cb8667e-c8ee-5b94-910a-020706a18146', '1bd7b503-ae45-5f56-9875-25dc0c849ee7', null, 'adequacao_conduta', 'Adequação', 'selecao_unica', 2, false, true, '[{"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "adequada_com_ressalvas", "rotulo": "Adequada com ressalvas"}, {"codigo": "inadequada_tecnicamente", "rotulo": "Inadequada tecnicamente"}, {"codigo": "nao_realizada", "rotulo": "Não realizada"}, {"codigo": "realizada_tardiamente", "rotulo": "Realizada tardiamente"}, {"codigo": "documentacao_insuficiente_avaliar", "rotulo": "Documentação insuficiente para avaliar"}, {"codigo": "nao_aplicavel", "rotulo": "Não aplicável"}]'::jsonb, null, false, null, true),
  ('220205e8-1aff-5381-a137-b5bc89892a97', '1bd7b503-ae45-5f56-9875-25dc0c849ee7', null, 'natureza_divergencia', 'Natureza da divergência', 'selecao_multipla', 3, false, true, '[{"codigo": "diagnostica", "rotulo": "Diagnóstica"}, {"codigo": "terapeutica", "rotulo": "Terapêutica"}, {"codigo": "cirurgica", "rotulo": "Cirúrgica"}, {"codigo": "anestesica", "rotulo": "Anestésica"}, {"codigo": "medicamentosa", "rotulo": "Medicamentosa"}, {"codigo": "monitorizacao", "rotulo": "Monitorização"}, {"codigo": "seguimento", "rotulo": "Seguimento"}, {"codigo": "comunicacao", "rotulo": "Comunicação"}, {"codigo": "documentacao", "rotulo": "Documentação"}, {"codigo": "encaminhamento_transferencia", "rotulo": "Encaminhamento/transferência"}, {"codigo": "organizacional", "rotulo": "Organizacional"}, {"codigo": "outra", "rotulo": "Outra"}]'::jsonb, null, false, null, false),
  ('b082da68-ca86-5cbb-a85e-1f9a0c2c994a', '1bd7b503-ae45-5f56-9875-25dc0c849ee7', null, 'fundamentacao_tecnico_cientifica', 'Fundamentação técnico-científica', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('f2a74d18-1ca0-5468-b592-660b422e1f5b', 'f539debe-3f54-5041-ab58-3f2dee0fef16', null, 'componentes_avaliados', 'Componentes avaliados', 'selecao_multipla', 1, false, true, '[{"codigo": "estrutura_fisica", "rotulo": "Estrutura física"}, {"codigo": "disponibilidade_equipe", "rotulo": "Disponibilidade de equipe"}, {"codigo": "enfermagem", "rotulo": "Enfermagem"}, {"codigo": "equipe_multiprofissional", "rotulo": "Equipe multiprofissional"}, {"codigo": "protocolos", "rotulo": "Protocolos"}, {"codigo": "disponibilidade_exames", "rotulo": "Disponibilidade de exames"}, {"codigo": "medicamentos", "rotulo": "Medicamentos"}, {"codigo": "equipamentos", "rotulo": "Equipamentos"}, {"codigo": "centro_cirurgico", "rotulo": "Centro cirúrgico"}, {"codigo": "uti", "rotulo": "UTI"}, {"codigo": "controle_infeccao", "rotulo": "Controle de infecção"}, {"codigo": "comunicacao_entre_equipes", "rotulo": "Comunicação entre equipes"}, {"codigo": "regulacao_transferencia", "rotulo": "Regulação/transferência"}, {"codigo": "continuidade_assistencial", "rotulo": "Continuidade assistencial"}, {"codigo": "prontuario", "rotulo": "Prontuário"}, {"codigo": "resposta_intercorrencias", "rotulo": "Resposta às intercorrências"}, {"codigo": "outro", "rotulo": "Outro"}]'::jsonb, null, false, null, false),
  ('5c4f6886-c22a-54b0-97ff-cdfc17398421', 'f539debe-3f54-5041-ab58-3f2dee0fef16', null, 'resultado_prestacao', 'Resultado', 'selecao_unica', 2, false, true, '[{"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "adequada_com_ressalvas", "rotulo": "Adequada com ressalvas"}, {"codigo": "inadequada", "rotulo": "Inadequada"}, {"codigo": "falha_estrutural_identificada", "rotulo": "Falha estrutural identificada"}, {"codigo": "falha_organizacional_identificada", "rotulo": "Falha organizacional identificada"}, {"codigo": "falha_assistencial_identificada", "rotulo": "Falha assistencial identificada"}, {"codigo": "falha_documental_identificada", "rotulo": "Falha documental identificada"}, {"codigo": "nao_possivel_avaliar", "rotulo": "Não é possível avaliar"}]'::jsonb, null, false, null, true),
  ('05210a1d-90da-58dd-aead-78a529810c72', 'f539debe-3f54-5041-ab58-3f2dee0fef16', null, 'descricao_objetiva_inadequacao_falha', 'Descrição objetiva da inadequação/falha', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('d9fb9ca7-88ce-51e8-a693-45b6a8de21f6', 'f539debe-3f54-5041-ab58-3f2dee0fef16', null, 'profissional_setor_instituicao_relacionado', 'Profissional/setor/instituição relacionado', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('b5313001-d8c2-5d24-a76d-4b29a93cf55c', 'f539debe-3f54-5041-ab58-3f2dee0fef16', null, 'repercussao_clinica_potencial_observada', 'Repercussão clínica potencial/observada', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('6e414456-1d8e-5bea-917e-57e9a20b0ce4', '3d99aefc-1290-5d04-b394-7f030fa219b9', null, 'confronto_padrao_tecnico', 'Confronto com o padrão técnico', 'tabela', 1, false, true, null, '{"linhas": [], "linhas_dinamicas": true, "colunas": [{"codigo": "questao_clinica", "rotulo": "Questão clínica", "tipo": "texto_livre"}, {"codigo": "padrao_tecnico_esperado", "rotulo": "Padrão técnico esperado", "tipo": "texto_livre"}, {"codigo": "fonte_diretriz", "rotulo": "Fonte/diretriz", "tipo": "texto_livre"}, {"codigo": "conduta_documentada", "rotulo": "Conduta documentada", "tipo": "texto_livre"}, {"codigo": "divergencia", "rotulo": "Divergência", "tipo": "texto_livre"}, {"codigo": "relevancia_clinica", "rotulo": "Relevância clínica", "tipo": "texto_livre"}]}'::jsonb, false, null, false),
  ('06b7c72d-b7b6-5311-9b6d-84835fd8dd28', '3d99aefc-1290-5d04-b394-7f030fa219b9', null, 'classificacao_global_confronto', 'Classificação global do confronto', 'selecao_unica', 2, false, true, '[{"codigo": "condutas_compativeis_padrao_tecnico", "rotulo": "Condutas compatíveis com o padrão técnico"}, {"codigo": "compativeis_com_ressalvas", "rotulo": "Compatíveis com ressalvas"}, {"codigo": "divergencias_tecnicas_identificadas", "rotulo": "Divergências técnicas identificadas"}, {"codigo": "elementos_insuficientes_confronto_seguro", "rotulo": "Elementos insuficientes para confronto seguro"}]'::jsonb, null, false, null, true),
  ('8147a78c-5e83-519a-a80e-6736f8aeabb1', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'classificacao_medico_pericial_desfecho', 'Classificação médico-pericial', 'selecao_unica', 1, false, true, '[{"codigo": "evolucao_natural_doenca", "rotulo": "Evolução natural da doença"}, {"codigo": "complicacao_conhecida_possivel", "rotulo": "Complicação conhecida e possível"}, {"codigo": "complicacao_nao_evitavel_elementos_disponiveis", "rotulo": "Complicação não evitável pelos elementos disponíveis"}, {"codigo": "evento_adverso", "rotulo": "Evento adverso"}, {"codigo": "evento_adverso_potencialmente_evitavel", "rotulo": "Evento adverso potencialmente evitável"}, {"codigo": "dano_relacionado_assistencia", "rotulo": "Dano relacionado à assistência"}, {"codigo": "dano_parcialmente_relacionado_assistencia", "rotulo": "Dano parcialmente relacionado à assistência"}, {"codigo": "dano_sem_relacao_demonstravel_assistencia", "rotulo": "Dano sem relação demonstrável com a assistência"}, {"codigo": "indeterminado", "rotulo": "Indeterminado"}]'::jsonb, null, false, null, true),
  ('527c393c-f1a1-5b09-9a35-b6194981ef86', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'dano_alegado', 'Dano alegado', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('53c4ba7c-f22e-5312-a3d1-3bd1e6274fc9', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'dano_objetivamente_demonstrado', 'Dano objetivamente demonstrado', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('1aba1787-a4a6-5adb-b880-cecac0be9cd8', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'data_inicio_dano', 'Data de início', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('a73f63a6-ec7b-55dc-9565-c9511377e114', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'duracao_dano', 'Duração', 'texto_livre', 5, false, true, null, null, false, null, false),
  ('bd153fce-b182-5b42-826d-a39877ea88e6', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'tratamentos_adicionais_decorrentes', 'Tratamentos adicionais decorrentes', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('c926d737-0210-53ab-a40d-e4141ab654f6', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'sequelas_atuais', 'Sequelas atuais', 'texto_livre', 7, false, true, null, null, false, null, false),
  ('d2d67f3a-30c0-569d-9b3e-fd0b9e1c7362', 'b10b32d8-c9e5-56de-adc2-47342ae34d58', null, 'prognostico', 'Prognóstico', 'texto_livre', 8, false, true, null, null, false, null, false),
  ('a802a1b3-c4db-5afc-961c-af3c74828c7f', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'criterios_analisados', 'Critérios analisados', 'selecao_multipla', 1, false, true, '[{"codigo": "temporalidade", "rotulo": "Temporalidade"}, {"codigo": "plausibilidade_biologica_fisiopatologica", "rotulo": "Plausibilidade biológica/fisiopatológica"}, {"codigo": "mecanismo", "rotulo": "Mecanismo"}, {"codigo": "topografia", "rotulo": "Topografia"}, {"codigo": "continuidade_sintomatica", "rotulo": "Continuidade sintomática"}, {"codigo": "estado_anterior", "rotulo": "Estado anterior"}, {"codigo": "causas_alternativas", "rotulo": "Causas alternativas"}, {"codigo": "concausas", "rotulo": "Concausas"}, {"codigo": "evolucao_esperada_sem_conduta_questionada", "rotulo": "Evolução esperada sem a conduta questionada"}, {"codigo": "influencia_acao_omissao_sobre_desfecho", "rotulo": "Influência da ação/omissão sobre o desfecho"}, {"codigo": "resposta_intervencoes_posteriores", "rotulo": "Resposta a intervenções posteriores"}]'::jsonb, null, false, null, false),
  ('10b60953-d7c6-5715-a62a-de9364161692', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'nexo_causal_resultado', 'Resultado', 'selecao_unica', 2, false, true, '[{"codigo": "nexo_causal_direto", "rotulo": "Nexo causal direto"}, {"codigo": "nexo_concausal", "rotulo": "Nexo concausal"}, {"codigo": "nexo_parcial", "rotulo": "Nexo parcial"}, {"codigo": "ausencia_nexo_causal_demonstravel", "rotulo": "Ausência de nexo causal demonstrável"}, {"codigo": "nexo_indeterminado", "rotulo": "Nexo indeterminado"}, {"codigo": "elementos_insuficientes", "rotulo": "Elementos insuficientes"}]'::jsonb, null, false, null, true),
  ('5c1bdbfa-f34d-5082-a702-12b558343d8f', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'concausas_causas_alternativas', 'Concausas/causas alternativas', 'texto_livre', 3, false, true, null, null, false, null, false),
  ('71f21b75-6aea-5c9a-b044-6a72076946e6', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'fundamentacao_causal', 'Fundamentação causal', 'texto_livre', 4, false, true, null, null, false, null, false),
  ('d485f0ba-d1e5-5a60-998d-2f2612b25893', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'probabilidade_evitar_reduzir_dano', 'Na hipótese de adoção da conduta tecnicamente esperada, havia probabilidade médico-clínica razoável de evitar ou reduzir o dano?', 'selecao_unica', 5, false, true, '[{"codigo": "sim", "rotulo": "Sim"}, {"codigo": "nao", "rotulo": "Não"}, {"codigo": "possivelmente", "rotulo": "Possivelmente"}, {"codigo": "nao_possivel_determinar", "rotulo": "Não é possível determinar"}]'::jsonb, null, false, null, true),
  ('6ea5d57b-0b3d-5c26-b15a-216be4e09c28', '26db7016-dd3c-575c-9de8-028a1d3e9eb1', null, 'fundamentacao_oportunidade_terapeutica', 'Fundamentação da oportunidade terapêutica', 'texto_livre', 6, false, true, null, null, false, null, false),
  ('1c2a92b3-8696-5b72-a599-f0accb9e2e0e', '98d679ca-f7c7-5026-95d5-5d6544965105', null, 'matriz_agentes', 'Matriz por agente', 'tabela', 1, false, true, null, '{"linhas": [], "linhas_dinamicas": true, "colunas": [{"codigo": "agente", "rotulo": "Agente", "tipo": "texto_livre"}, {"codigo": "conduta_atribuida", "rotulo": "Conduta atribuída", "tipo": "texto_livre"}, {"codigo": "adequacao_tecnica", "rotulo": "Adequação técnica", "tipo": "texto_livre"}, {"codigo": "dano_relacionado", "rotulo": "Dano relacionado", "tipo": "texto_livre"}, {"codigo": "nexo", "rotulo": "Nexo", "tipo": "texto_livre"}, {"codigo": "fundamentacao", "rotulo": "Fundamentação", "tipo": "texto_livre"}]}'::jsonb, false, null, true),
  ('fa488613-3507-5e7e-92c1-b485aa83e334', 'e3f7e1ec-918d-5d2b-a547-df3704947483', null, 'camada_adequacao_tecnico_assistencial', '1. Adequação técnico-assistencial', 'selecao_unica', 1, false, true, '[{"codigo": "adequada", "rotulo": "Adequada"}, {"codigo": "adequada_com_ressalvas", "rotulo": "Adequada com ressalvas"}, {"codigo": "inadequada", "rotulo": "Inadequada"}, {"codigo": "nao_avaliavel", "rotulo": "Não avaliável"}]'::jsonb, null, false, null, true),
  ('5075f6c0-ee3c-55a5-9e0f-342ed4d7bbd8', 'e3f7e1ec-918d-5d2b-a547-df3704947483', null, 'camada_existencia_dano', '2. Existência de dano', 'selecao_unica', 2, false, true, '[{"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "presente_temporario", "rotulo": "Presente temporário"}, {"codigo": "presente_permanente", "rotulo": "Presente permanente"}, {"codigo": "indeterminado", "rotulo": "Indeterminado"}]'::jsonb, null, false, null, true),
  ('08864d10-63bf-54ea-b74e-0e1d7f94163f', 'e3f7e1ec-918d-5d2b-a547-df3704947483', null, 'camada_relacao_causal', '3. Relação causal', 'selecao_unica', 3, false, true, '[{"codigo": "direta", "rotulo": "Direta"}, {"codigo": "concausal", "rotulo": "Concausal"}, {"codigo": "parcial", "rotulo": "Parcial"}, {"codigo": "ausente", "rotulo": "Ausente"}, {"codigo": "indeterminada", "rotulo": "Indeterminada"}]'::jsonb, null, false, null, true),
  ('26407341-afe3-5832-9fcd-857c1990f582', 'ba332ded-e910-57e3-aa0f-4a0d85130236', null, 'discussao_individualizada', 'Discussão individualizada', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('2ad09bf2-1cd1-5792-88b1-432173811c7d', '9cf2be03-f9f3-55e6-ad66-0d74b6c6f0fa', null, 'conclusao_modelo_automatico', 'Modelo automático de conclusão', 'selecao_unica', 1, false, true, '[{"codigo": "inadequacao_com_nexo", "rotulo": "Inadequação com nexo", "texto_automatico": "Foram identificadas divergências entre a assistência documentada e o padrão técnico aplicável ao contexto clínico, especificamente quanto a {{descricao_objetiva_inadequacao_falha}}. Tais inadequações apresentam {{nexo_causal_resultado}} com o dano {{dano_objetivamente_demonstrado}}, pelos fundamentos médico-periciais expostos."}, {"codigo": "inadequacao_sem_nexo_demonstrado", "rotulo": "Inadequação sem nexo demonstrado", "texto_automatico": "Foram identificadas inadequações técnico-assistenciais/documentais quanto a {{descricao_objetiva_inadequacao_falha}}; contudo, os elementos disponíveis não demonstram relação causal suficiente entre tais inadequações e o dano {{dano_objetivamente_demonstrado}}."}, {"codigo": "complicacao_sem_inadequacao_demonstrada", "rotulo": "Complicação sem inadequação demonstrada", "texto_automatico": "O desfecho adverso constatado mostra-se compatível com complicação reconhecida de {{queixa_diagnostico_inicial}}, não tendo sido demonstrada, nos elementos analisados, inadequação técnico-assistencial causalmente relacionada ao dano."}, {"codigo": "insuficiencia_documental", "rotulo": "Insuficiência documental", "texto_automatico": "A documentação disponibilizada não permite reconstrução suficientemente segura da assistência prestada, considerando a classificação documental de {{classificacao_situacao_documental}}, impossibilitando conclusão técnico-pericial definitiva quanto à adequação da conduta e/ou sua relação causal com o desfecho."}]'::jsonb, null, false, null, true),
  ('12a163b9-fc6e-51f5-a357-6f26fbcc089a', '9cf2be03-f9f3-55e6-ad66-0d74b6c6f0fa', null, 'conclusao_individualizada', 'Conclusão individualizada', 'texto_livre', 2, false, true, null, null, false, null, false),
  ('2e1c673e-fc4b-50dd-b291-f831c5540c73', '09522b45-0c2c-54d5-99a6-207bf21591ed', null, 'cidade_uf_assinatura', 'Cidade/UF', 'texto_livre', 1, false, true, null, null, false, null, false),
  ('12757c43-3336-5c2b-bd21-e0c8aa452335', '09522b45-0c2c-54d5-99a6-207bf21591ed', null, 'data_assinatura', 'Data', 'texto_livre', 2, false, true, null, null, false, null, false);
