-- ============================================================================
-- Normaliza placeholders "crus" nos 3 seeds mais antigos (curatela,
-- previdenciario, trabalhista) — revisão do catálogo, item 2.
-- ============================================================================
-- Contexto: esses 3 seeds usavam {{token}} tanto para referência a campo real
-- (auto-resolvida por narrativo.ts) quanto para marcador de preenchimento
-- manual (que vazava CRU no laudo, pois resolverPlaceholders faz `return match`
-- quando o token não é campo). Os 7 tipos mais novos já padronizam: {{}} só
-- para campo real; [colchetes] para preenchimento manual.
--
-- Esta migration troca, SOMENTE nos campos/opções/seções afetados, todo
-- {{token}} órfão por [token]. Preserva {{token}} de campo real e os tokens
-- agregados do compilador ({{total_documentos}}, {{total_paginas}},
-- {{categorias_principais}}). Não recria seed nem toca nos 7 tipos novos.
-- Gerada por scratchpad/gen_migracoes_correcao.py a partir dos .sql aplicados.
-- ============================================================================

-- 10 seções, 2 campos (template), 3 campos (opções)

-- [curatela] secao avaliacao_funcionalidade: {{funcionalidade_abvd_grau}}, {{funcionalidade_aivd_grau}}, {{funcionalidade_atividades_criticas}}, {{funcionalidade_tipo_auxilio}}
update public.secoes set texto_automatico_template = 'Quanto à funcionalidade, apresenta [funcionalidade_abvd_grau] para as atividades básicas da vida diária e [funcionalidade_aivd_grau] de dependência para as atividades instrumentais, necessitando de [funcionalidade_tipo_auxilio] principalmente para [funcionalidade_atividades_criticas].' where id = '647490b9-ed73-511f-8f3f-b6ca2a4dc76c';

-- [curatela] secao discussao_medico_legal: {{achados_clinicos_principais}}, {{alteracoes_cognitivas_psiquicas_principais}}, {{atividades_dependentes}}, {{grau_autonomia}}, {{grau_auxilio}}, {{preservacao_comprometimento_capacidade_decisoria}}, {{sintese_capacidade_civil}}
update public.secoes set texto_automatico_template = 'A existência de diagnóstico médico não determina, isoladamente, incapacidade civil. A análise médico-pericial deve estabelecer se as alterações clínicas identificadas repercutem concretamente sobre as capacidades necessárias à compreensão, deliberação, manifestação da vontade, autodeterminação e exercício dos atos da vida civil. No caso em análise, o(a) periciando(a) apresenta {{diagnostico_principal}}, caracterizado por [achados_clinicos_principais], observando-se ao exame [alteracoes_cognitivas_psiquicas_principais]. Do ponto de vista funcional, apresenta [grau_autonomia], necessitando de [grau_auxilio] para [atividades_dependentes]. Quanto à capacidade decisória, verifica-se [preservacao_comprometimento_capacidade_decisoria] da capacidade de compreender informações, avaliar consequências, comparar alternativas, manifestar escolhas e reconhecer riscos relacionados aos atos avaliados. A análise conjunta desses elementos permite estabelecer que [sintese_capacidade_civil]. A eventual indicação de curatela deve ser interpretada de maneira individualizada, proporcional às necessidades concretamente identificadas e com preservação máxima possível da autonomia e da manifestação de vontade do(a) periciando(a).' where id = 'ff1784c0-5149-5836-a94b-9bea1d7cd633';

-- [previdenciario] secao discussao_medico_pericial: {{achados_objetivos_exame}}, {{compatibilidade_atividade}}, {{funcoes_comprometidas}}
update public.secoes set texto_automatico_template = 'A existência de doença ou diagnóstico médico não caracteriza, isoladamente, incapacidade laborativa. No presente caso, o(a) periciando(a) apresenta {{diagnostico_informado}} ({{cid_informado}}), cuja existência encontra-se {{condicao_objetivamente_demonstrada}} pelos elementos documentais e clínicos analisados. Ao exame pericial foram identificados [achados_objetivos_exame], determinando limitações relacionadas a [funcoes_comprometidas]. A atividade habitual de {{profissao_habitual}} demanda {{exigencias_ocupacionais}}. Da correlação entre os achados clínicos, a repercussão funcional e as exigências da atividade, verifica-se [compatibilidade_atividade] entre o estado de saúde atual e o exercício da ocupação habitual. Quando presente incapacidade, esta se caracteriza como {{grau_incapacidade}}, {{duracao_incapacidade}} e {{abrangencia_profissional}}, com capacidade residual {{capacidade_residual}} e possibilidade de reabilitação {{reabilitacao_profissional_indicacao}}.' where id = '59e3d96a-0477-5aa0-90f3-824a366f44cb';

-- [previdenciario] secao correlacao_medico_funcional_atividade_laboral: {{achados_objetivos_exame}}, {{compatibilidade_atividade}}, {{funcoes_afetadas}}
update public.secoes set texto_automatico_template = 'O(a) periciando(a) apresenta {{diagnostico_informado}}, com achados objetivos caracterizados por [achados_objetivos_exame]. Tais alterações determinam {{repercussao_funcional_objetiva}} de limitação para [funcoes_afetadas], as quais se mostram [compatibilidade_atividade] com as exigências da atividade habitual de {{profissao_habitual}}.' where id = 'a66ceb5a-70bf-5d34-8496-56b659168971';

-- [trabalhista] secao discussao_medico_pericial: {{compatibilidade_temporal}}, {{danos_limitacoes}}, {{diagnostico_cid}}, {{elementos_demonstracao}}, {{exposicoes_ocupacionais_descricao}}, {{fatores_etiologicos_literatura}}, {{fatores_individuais_extralaborais}}, {{impacto_laboral_descricao}}, {{intensidade_frequencia_duracao}}, {{sustenta_ou_nao_sustenta}}
update public.secoes set texto_automatico_template = 'O(a) periciando(a) apresenta [diagnostico_cid], demonstrado por [elementos_demonstracao]. A literatura reconhece como fatores etiológicos [fatores_etiologicos_literatura]. No caso concreto, foram identificadas exposições ocupacionais [exposicoes_ocupacionais_descricao], com intensidade, frequência e duração [intensidade_frequencia_duracao]. A relação temporal entre exposição e adoecimento mostrou-se [compatibilidade_temporal]. Foram ainda identificados [fatores_individuais_extralaborais]. A integração desses elementos [sustenta_ou_nao_sustenta] participação do trabalho na gênese ou agravamento do quadro. As repercussões atuais consistem em [danos_limitacoes], com impacto laboral [impacto_laboral_descricao].' where id = '1a6025d3-4aa4-56ea-827f-f0cc3b7d2342';

-- [trabalhista] secao diagnostico_nosologico: {{cid_principal_tabela}}, {{diagnostico_principal_tabela}}, {{elementos_fundamentacao}}
update public.secoes set texto_automatico_template = 'O exame pericial permite estabelecer o diagnóstico de [diagnostico_principal_tabela], CID [cid_principal_tabela], fundamentado em [elementos_fundamentacao].' where id = '3efa1e08-b6ce-5182-96b1-16441a8236d6';

-- [trabalhista] secao matriz_analise_nexo_causal: {{agravo}}, {{permite_ou_nao_permite}}, {{trabalho}}
update public.secoes set texto_automatico_template = 'A análise dos critérios de exposição, temporalidade, plausibilidade biológica, compatibilidade clínico-ocupacional e fatores concorrentes [permite_ou_nao_permite] estabelecer relação causal entre [agravo] e [trabalho].' where id = '7410b528-ae04-5bf7-902c-7930d9ab5dc2';

-- [trabalhista] secao avaliacao_capacidade_laborativa: {{atividades_afetadas}}, {{condicao}}
update public.secoes set texto_automatico_template = 'Na data da perícia, o(a) periciando(a) apresenta {{capacidade_atual}}, de grau {{grau}}, com repercussão sobre [atividades_afetadas], em razão de [condicao].' where id = 'afed002e-8e82-5841-94cd-3148e22d0d10';

-- [trabalhista] secao analise_concausalidade: {{atuou_ou_nao_atuou}}, {{concausalidade_ou_ausencia}}
update public.secoes set texto_automatico_template = 'O trabalho não se apresenta como causa exclusiva do agravo, porém [atuou_ou_nao_atuou] como fator {{papel_trabalho}}, caracterizando [concausalidade_ou_ausencia] sob a perspectiva médico-pericial.' where id = 'b2213e8d-bb33-53b7-9578-a85a43d74559';

-- [trabalhista] secao necessidade_pericia_posto_trabalho: {{suficiencia_elementos}}
update public.secoes set texto_automatico_template = 'Os elementos atuais são [suficiencia_elementos] para análise das condições de trabalho. Recomenda-se {{necessidade_complementacao}}, com o objetivo específico de esclarecer {{objetivo_tecnico_especifico_diligencia}}.' where id = 'e65b7dac-6fed-591b-bfc0-26cc0d0e0ce1';

-- [previdenciario] campo sistema_musculoesqueletico (template): {{me_achados_gerais}}, {{me_movimentos_segmentos}}, {{me_repercussao_funcional}}
update public.campos_secao set texto_automatico_template = 'O exame musculoesquelético evidenciou [me_achados_gerais], com repercussão funcional [me_repercussao_funcional] sobre [me_movimentos_segmentos].' where id = '8ab54efc-c86f-5a64-b14c-fa7584665940';

-- [trabalhista] campo sistema_musculoesqueletico (template): {{me_achados_gerais}}, {{me_repercussao_funcional}}, {{me_segmentos_funcoes}}
update public.campos_secao set texto_automatico_template = 'O exame musculoesquelético evidenciou [me_achados_gerais], com repercussão funcional [me_repercussao_funcional] sobre [me_segmentos_funcoes].' where id = 'f74983d2-0eef-563c-b15d-691c0bc9ce53';

-- [curatela] campo conclusao_modelo_automatico (opções): {{atos_afetados}}, {{dominios_comprometidos}}, {{dominios_preservados}}, {{funcoes_comprometidas}}, {{tipo_complementacao_necessaria}}
update public.campos_secao set opcoes = '[{"codigo": "capacidade_preservada", "rotulo": "Capacidade preservada", "texto_automatico": "Diante dos elementos médico-periciais obtidos, não foram identificadas alterações clínicas, cognitivas ou funcionais de magnitude suficiente para comprometer significativamente a capacidade do(a) periciando(a) de compreender, deliberar e manifestar sua vontade em relação aos atos avaliados, não se evidenciando, sob a perspectiva médico-pericial, necessidade atual de representação ou assistência contínua para atos patrimoniais e negociais."}, {"codigo": "comprometimento_parcial_setorial", "rotulo": "Comprometimento parcial/setorial", "texto_automatico": "O(a) periciando(a) apresenta {{diagnostico_principal}}, com repercussão sobre [funcoes_comprometidas]. Mantém capacidade para [dominios_preservados], porém apresenta prejuízo relevante para [dominios_comprometidos], especialmente quanto a [atos_afetados]. Sob a perspectiva médico-pericial, necessita de apoio/assistência para esses atos específicos, devendo ser preservada sua autonomia nos demais domínios em que demonstra compreensão, discernimento e capacidade de manifestação da vontade."}, {"codigo": "comprometimento_acentuado", "rotulo": "Comprometimento acentuado", "texto_automatico": "O(a) periciando(a) apresenta {{diagnostico_principal}}, associado a comprometimento significativo de [funcoes_comprometidas], com repercussão relevante sobre a capacidade de compreender informações, avaliar consequências, deliberar e administrar autonomamente atos de natureza patrimonial e negocial. Sob a perspectiva médico-pericial, evidencia-se necessidade contínua de proteção e auxílio de terceiros nesses domínios, preservando-se, sempre que possível, sua participação nas decisões e a manifestação de suas preferências e vontade."}, {"codigo": "inconclusivo", "rotulo": "Inconclusivo", "texto_automatico": "Os elementos atualmente disponíveis não permitem estabelecer, com segurança médico-pericial suficiente, a extensão da repercussão da condição clínica sobre a capacidade civil do(a) periciando(a), sendo necessária complementação por [tipo_complementacao_necessaria] antes da emissão de conclusão definitiva."}]'::jsonb where id = '4d18b3ae-374e-5544-9cd5-43073c2c3207';

-- [previdenciario] campo conclusao_modelo_automatico (opções): {{achados_objetivos_exame}}, {{data_periodo_recuperacao_estimada}}, {{evento_causador_sequela}}
update public.campos_secao set opcoes = '[{"codigo": "capacidade_preservada", "rotulo": "Capacidade preservada", "texto_automatico": "O(a) periciando(a) apresenta {{conclusao_diagnostico_principal}}, contudo os achados clínicos objetivos e as repercussões funcionais identificadas na presente avaliação não demonstram limitação de magnitude suficiente para impedir o exercício da atividade habitual de {{profissao_habitual}}. Sob a perspectiva médico-pericial, encontra-se preservada a capacidade laborativa na data do exame."}, {"codigo": "incapacidade_temporaria", "rotulo": "Incapacidade temporária", "texto_automatico": "O(a) periciando(a) apresenta {{conclusao_diagnostico_principal}}, associado a [achados_objetivos_exame], determinando limitações funcionais incompatíveis, no momento, com as exigências da atividade habitual de {{profissao_habitual}}. Caracteriza-se incapacidade laborativa {{conclusao_grau_incapacidade}}, de natureza temporária, com DII estabelecida em {{conclusao_dii}} e recuperação estimada para [data_periodo_recuperacao_estimada], condicionada à evolução clínica e terapêutica."}, {"codigo": "incapacidade_permanente_com_reabilitacao", "rotulo": "Incapacidade permanente com reabilitação", "texto_automatico": "O conjunto dos achados médico-periciais demonstra limitação funcional permanente incompatível com o retorno à atividade habitual de {{profissao_habitual}}. Entretanto, encontram-se preservadas capacidades funcionais que permitem considerar viável a reabilitação profissional para atividade compatível com as restrições identificadas."}, {"codigo": "incapacidade_permanente_sem_reabilitacao", "rotulo": "Incapacidade permanente sem possibilidade de reabilitação", "texto_automatico": "O conjunto dos achados clínicos e funcionais evidencia comprometimento de caráter permanente e extensão suficiente para inviabilizar o desempenho da atividade habitual e de outras atividades compatíveis capazes de garantir subsistência, não se identificando, sob a perspectiva médico-funcional atual, potencial razoável de reabilitação profissional."}, {"codigo": "reducao_permanente_capacidade", "rotulo": "Redução permanente da capacidade", "texto_automatico": "O(a) periciando(a) apresenta sequela consolidada decorrente de [evento_causador_sequela], determinando redução permanente da capacidade para o desempenho da atividade habitualmente exercida, embora permaneça apto(a) ao trabalho mediante maior esforço, adaptação ou redução funcional correspondente às limitações descritas."}]'::jsonb where id = 'ec4bb767-df1e-5eff-996e-61f2dcc1f9dc';

-- [trabalhista] campo conclusao_modelo_automatico (opções): {{atividades_residuais}}, {{condicao}}, {{danos_limitacoes}}, {{descricao_repercussoes}}, {{fator_exposicao}}, {{fatores_nao_laborais}}, {{funcao_exigencias}}, {{restricoes_adaptacoes}}, {{situacao_capacidade}}, {{tarefas_funcao}}, {{tratamento_periodo}}
update public.campos_secao set opcoes = '[{"codigo": "sem_nexo_sem_incapacidade", "rotulo": "Sem nexo e sem incapacidade", "texto_automatico": "O(a) periciando(a) apresenta {{conclusao_diagnostico_principal}}, porém os elementos clínicos, documentais, ocupacionais e etiológicos analisados não demonstram relação causal ou concausal tecnicamente sustentada com o trabalho objeto da demanda. Na data da perícia, não se identificam limitações funcionais de magnitude suficiente para caracterizar incapacidade laborativa."}, {"codigo": "nexo_causal", "rotulo": "Nexo causal", "texto_automatico": "O conjunto médico-pericial demonstra diagnóstico de {{conclusao_diagnostico_principal}}, exposição ocupacional a [fator_exposicao], compatibilidade temporal e biológica e coerência clínico-ocupacional suficientes para estabelecer nexo causal entre o agravo e o trabalho exercido. As repercussões atuais consistem em [danos_limitacoes], com capacidade laborativa [situacao_capacidade]."}, {"codigo": "concausalidade", "rotulo": "Concausalidade", "texto_automatico": "A condição apresenta etiologia multifatorial, com participação de [fatores_nao_laborais]. Entretanto, as condições de trabalho demonstradas atuaram como fator {{papel_trabalho}}, caracterizando concausalidade médico-pericial. As repercussões funcionais atuais são [descricao_repercussoes]."}, {"codigo": "incapacidade_temporaria", "rotulo": "Incapacidade temporária", "texto_automatico": "O(a) periciando(a) apresenta limitação funcional temporária decorrente de [condicao], incompatível atualmente com [funcao_exigencias]. Estima-se necessidade de [tratamento_periodo], devendo a capacidade ser reavaliada conforme evolução clínica."}, {"codigo": "reducao_permanente_capacidade", "rotulo": "Redução permanente da capacidade", "texto_automatico": "Há sequela consolidada com redução funcional permanente para [tarefas_funcao], permanecendo capacidade residual para [atividades_residuais], mediante [restricoes_adaptacoes]."}]'::jsonb where id = '7ad2ef4e-d524-5843-9034-70aa6aed1302';
